/**
 * Catalog 1 of 3 — the noticing rooms. 26 games.
 *
 *   Feelings Room ·  8 · trains step 1, naming what you feel
 *   Body Detective · 7 · trains step 2, finding it in the body
 *   Thought Room  · 11 · trains step 3, hearing what the mind says
 *
 * Scripts are lifted from MIND_GYM_TEACHING_MOVES.md wherever that document
 * has one, near-verbatim and on purpose: those lines are tested, and the
 * temptation to improve them is exactly how the moral creeps back in.
 */

import type { Game } from '../types';

export const AWARENESS_GAMES: Game[] = [
  /* ══ Feelings Room · 8 ══════════════════════════════════════════════ */
  {
    id: 'emotion-detective',
    room: 'feelings',
    name: 'Emotion Detective',
    band: 'A',
    move: 'practice',
    flagship: true,
    trains: 'Reading feelings in other people',
    opener: 'Look at them. What do you reckon?',
    close: 'You found more than one. That’s usually how people are.',
    engine: 'choose',
    rounds: [
      {
        scene: 'Nell is standing at the edge of the playground. Everyone else is already in a game.',
        prompt: 'What might Nell be feeling? Tap any that fit.',
        options: ['Left out', 'Shy', 'Cross', 'Sad', 'Fine, actually', 'Nervous'],
        multi: true,
        affirm: 'Other children pick different ones. They’re not wrong either.',
      },
      {
        scene: 'Theo’s tower fell over. Right at the end. He’s very still.',
        prompt: 'What might Theo be feeling?',
        options: ['Furious', 'Fed up', 'Like crying', 'Embarrassed', 'Ready to build it again'],
        multi: true,
        affirm: 'Still is not the same as fine. You spotted that.',
      },
      {
        scene: 'Amara got picked first. She’s not smiling.',
        prompt: 'What might be going on?',
        options: ['Worried she’ll be rubbish', 'Pleased but shy', 'Thinking about something else', 'I can’t tell'],
        multi: true,
        affirm: '“I can’t tell” is a proper answer. Nobody can always tell.',
      },
    ],
  },
  {
    id: 'feeling-match',
    room: 'feelings',
    name: 'Feeling Match',
    band: 'A',
    move: 'practice',
    trains: 'Things happen, then feelings come',
    opener: 'Same thing happens to everyone. Different feelings come out.',
    close: 'Nobody gets the same feeling from the same thing. Not even nearly.',
    engine: 'choose',
    rounds: [
      { scene: 'Sports day is tomorrow.', prompt: 'What might that bring up?', options: ['Excited', 'Dreading it', 'Both at once', 'Nothing much'], multi: true },
      { scene: 'A new person is joining your class.', prompt: 'What might that bring up?', options: ['Curious', 'Nervous', 'Pleased', 'Bothered', 'Nothing much'], multi: true },
      { scene: 'Your grown-up says “we need to talk”.', prompt: 'What might that bring up?', options: ['Worried', 'In trouble', 'Confused', 'Calm — could be anything'], multi: true, affirm: 'Everyone picked “in trouble” too. It hardly ever is.' },
    ],
  },
  {
    id: 'feeling-mix',
    room: 'feelings',
    name: 'Feeling Mix',
    band: 'B',
    move: 'image',
    trains: 'Two feelings, both true at once',
    opener: 'The last day of a holiday. That one.',
    close: 'Two feelings, full size, at the same time. Neither one cancelled the other.',
    engine: 'dial',
    dual: { a: 'Happy', b: 'Sad' },
    rounds: [
      { prompt: 'The last day of a holiday. Set them both.', steps: ['a whisper', 'quite there', 'quite loud', 'all of it'], affirm: 'You didn’t have to turn one down to turn the other up.' },
      { prompt: 'Your best friend is moving to a brilliant new school.', steps: ['a whisper', 'quite there', 'quite loud', 'all of it'] },
      { prompt: 'A wobbly tooth. You want it out — and you don’t.', steps: ['a whisper', 'quite there', 'quite loud', 'all of it'], affirm: 'That’s not you being confused. That’s just how people are built.' },
    ],
  },
  {
    id: 'volume-dial',
    room: 'feelings',
    name: 'Volume Dial',
    band: 'A',
    move: 'practice',
    trains: 'There’s a word for every size',
    opener: 'Same feeling. Turn it up and it gets a new name.',
    close: 'Annoyed and furious are the same feeling at different volumes. Now you’ve got words for both.',
    engine: 'dial',
    rounds: [
      { prompt: 'Turn up the cross one.', steps: ['Bothered', 'Annoyed', 'Cross', 'Angry', 'Furious'] },
      { prompt: 'Turn up the worried one.', steps: ['Unsure', 'Uneasy', 'Worried', 'Scared', 'Terrified'] },
      { prompt: 'Turn up the happy one.', steps: ['Alright', 'Pleased', 'Happy', 'Delighted', 'Over the moon'], affirm: 'The happy one has just as many words. People forget that.' },
      { prompt: 'Turn up the sad one.', steps: ['Flat', 'Down', 'Sad', 'Miserable', 'Heartbroken'] },
    ],
  },
  {
    id: 'same-thing',
    room: 'feelings',
    name: 'Same Thing, Different People',
    band: 'A',
    move: 'practice',
    trains: 'Feelings aren’t automatic',
    opener: 'Two people. Exact same afternoon.',
    close: 'Same thing happened. Different feelings came. Both of them are fine.',
    engine: 'choose',
    rounds: [
      { scene: 'The class is told there’s a spelling test on Friday. Kai grins. Sof goes quiet.', prompt: 'Who’s right?', options: ['Kai', 'Sof', 'Both of them'], affirm: 'Both. It isn’t the test that makes the feeling — it’s the person it lands on.' },
      { scene: 'The lights go out in a storm. One of them laughs. One of them freezes.', prompt: 'What made the difference?', options: ['One is braver', 'They’re thinking different things', 'One likes the dark', 'I don’t know'], affirm: 'Something different is going on inside each of them. You can’t see it from outside.' },
      { scene: 'Someone shouts your name across the playground.', prompt: 'What would you feel?', options: ['Pleased', 'Embarrassed', 'On guard', 'Depends who it is'], multi: true },
    ],
  },
  {
    id: 'inside-weather',
    room: 'feelings',
    name: 'Inside Weather',
    band: 'S',
    move: 'image',
    trains: 'Feelings change, like weather does',
    opener: 'What’s the weather doing in you today?',
    close: 'Nobody ever stopped the weather. It just goes and does something else in a bit.',
    engine: 'choose',
    rounds: [
      { prompt: 'What’s it like inside you today?', options: ['☀️ Sunny', '🌦️ Drizzly', '⛈️ Stormy', '🌫️ Foggy', '🌤️ Bright with clouds', '❄️ Cold and still'] },
      { prompt: 'And this morning — was it the same?', options: ['Same all day', 'It changed', 'It’s changed twice already', 'I can’t remember'], affirm: 'It changed. Weather does that. Yours does too.' },
      { prompt: 'What would you like it to do next?', options: ['Brighten up', 'Stay just like this', 'Calm down a bit', 'I don’t mind'] },
    ],
  },
  {
    id: 'feeling-changed',
    room: 'feelings',
    name: 'The Feeling Changed',
    band: 'A',
    move: 'experiment',
    trains: 'Spotting the moment a feeling turns',
    opener: 'Watch for the bit where it turns. It’s quick.',
    close: 'You found the turn. Feelings do that all day, and mostly nobody notices.',
    engine: 'story',
    panels: [
      { kind: 'line', text: 'Jo woke up excited. Today is the trip.' },
      { kind: 'line', text: 'Then the coach was late. Then it started raining.' },
      { kind: 'line', text: 'By the time they got on, Jo wasn’t excited any more. Jo was fed up.' },
      { kind: 'choice', prompt: 'Where did it turn?', options: ['When the coach was late', 'When it rained', 'Somewhere in between', 'When Jo gave up on it being good'] },
      { kind: 'replay', text: 'Watch it again, from “{choice}”. See it go? Excited, then not.' },
      { kind: 'line', text: 'Then someone put a song on, and about four minutes later Jo was singing.' },
      { kind: 'line', text: 'It turned again. Nobody made it turn.', who: 'chirpy' },
    ],
  },
  {
    id: 'blue-cup',
    room: 'feelings',
    name: 'The Blue Cup',
    band: 'S',
    move: 'image',
    trains: 'Feelings pass — proof from your own life',
    opener: 'I want to tell you about when you were little.',
    close: 'It really was the worst thing, back then. It just isn’t any more.',
    engine: 'story',
    panels: [
      { kind: 'line', text: 'When you were little — really little — there was a cup.' },
      { kind: 'line', text: 'You wanted the blue one. Someone gave you the red one.' },
      { kind: 'line', text: 'And it was the worst thing that had ever happened.' },
      { kind: 'choice', prompt: 'Do you still mind about the blue cup?', options: ['No', 'A bit', 'I don’t remember it at all'] },
      { kind: 'line', text: 'It wasn’t silly. At the time it was enormous. That bit was real.' },
      { kind: 'line', text: 'It’s just that it went. Without you doing anything about it.', who: 'chirpy' },
      { kind: 'cards', prompt: 'What’s your blue cup? The thing that was enormous once.', cards: ['A toy that broke', 'A party I missed', 'A friend who moved', 'A day that went wrong', 'I can’t think of one'], land: 'That one’s smaller now than it was. You didn’t do anything. It just got smaller.' },
    ],
  },

  /* ══ Body Detective · 7 ═════════════════════════════════════════════ */
  {
    id: 'body-detective',
    room: 'body',
    name: 'Body Detective',
    band: 'A',
    move: 'practice',
    flagship: true,
    trains: 'Feelings show up in the body',
    opener: 'Somewhere in there, something is going on. Find it.',
    close: 'Feelings leave clues in the body. You just read some.',
    engine: 'body',
    rounds: [
      { prompt: 'Sam is about to go on stage. Where might Sam’s body be giving it away?', need: 2, affirm: 'Good spots. Nerves love the tummy and the hands.' },
      { prompt: 'Ada is furious. Where would you look?', need: 2, affirm: 'Cross usually turns up high — jaw, face, fists.' },
      { prompt: 'Now you. Right now, where is something happening?', need: 1, cantTell: 'I can’t tell right now', affirm: 'There’s no right place. Yours lives wherever yours lives.' },
    ],
  },
  {
    id: 'clue-hunt',
    room: 'body',
    name: 'Clue Hunt',
    band: 'A',
    move: 'experiment',
    trains: 'Checking in with yourself, one place at a time',
    opener: 'One bit at a time. We’re not in a rush.',
    close: 'You went round the whole lot. Some places had something, some didn’t. That’s normal.',
    engine: 'body',
    rounds: [
      { prompt: 'Start at the top. Anything going on in your head or your face?', cantTell: 'Nothing there' },
      { prompt: 'Now your chest. Is it fast, slow, tight, easy?', cantTell: 'Nothing there' },
      { prompt: 'Your tummy. Anything?', cantTell: 'Nothing there' },
      { prompt: 'Your hands. Are they still, or busy?', cantTell: 'Nothing there' },
      { prompt: 'Last one — your feet. Can you feel them inside your shoes?', cantTell: 'Not really', affirm: 'They were there the whole time, whether you were looking or not.' },
    ],
  },
  {
    id: 'clue-to-feeling',
    room: 'body',
    name: 'Clue → Feeling',
    band: 'A',
    move: 'practice',
    trains: 'Reading the body backwards into a feeling',
    opener: 'Backwards this time. Clue first, feeling after.',
    close: 'You read it backwards. That’s the detective bit.',
    engine: 'choose',
    rounds: [
      { scene: 'Tight fists. Hot face. Fast breathing.', prompt: 'What might be going on?', options: ['Angry', 'Scared', 'Just ran', 'Embarrassed'], multi: true, affirm: 'More than one fits. The body doesn’t label things for you.' },
      { scene: 'Heavy arms. Slow everything. Wanting to lie down.', prompt: 'What might be going on?', options: ['Sad', 'Tired', 'Fed up', 'Poorly'], multi: true },
      { scene: 'Fluttery tummy. Cold hands. Can’t sit still.', prompt: 'What might be going on?', options: ['Nervous', 'Excited', 'Both', 'Hungry'], multi: true, affirm: 'Nervous and excited use nearly the same body. Genuinely.' },
    ],
  },
  {
    id: 'jump-and-notice',
    room: 'body',
    name: 'Jump & Notice',
    band: 'S',
    move: 'experiment',
    trains: 'Proving you can feel what’s inside',
    opener: 'Right. Up you get. This one needs your actual legs.',
    close: 'You felt something happening inside you. That’s the whole skill. It works.',
    engine: 'timed',
    beats: [
      { kind: 'say', text: 'Stand up. Properly up.' },
      { kind: 'move', text: 'Jump. Ten times. Go on.', count: 10, after: 'Now stop. Stand completely still.' },
      { kind: 'hold', seconds: 6 },
      { kind: 'ask', prompt: 'What’s your heart doing?', options: ['Banging', 'Fast', 'Normal already', 'I can feel it in my ears'] },
      { kind: 'reveal', text: 'You could feel it, couldn’t you. You just found something happening inside you.' },
      { kind: 'say', text: 'That’s the game. Feelings do that too — they turn up somewhere in there.', who: 'chirpy' },
    ],
  },
  {
    id: 'where-does-it-live',
    room: 'body',
    name: 'Where Does It Live?',
    band: 'A',
    move: 'experiment',
    trains: 'Your body map is yours',
    opener: 'Everyone’s is different. Mine’s all in my ears.',
    close: 'My cross lives in my jaw. Someone else’s lives in their hands. Yours lives wherever yours lives.',
    engine: 'body',
    rounds: [
      { prompt: 'Where does cross live in you?', cantTell: 'I don’t know yet' },
      { prompt: 'Where does worried live?', cantTell: 'I don’t know yet' },
      { prompt: 'Where does excited live?', cantTell: 'I don’t know yet' },
      { prompt: 'And happy — where’s that one?', cantTell: 'I don’t know yet', affirm: 'That’s your map. Nobody else has that one.' },
    ],
  },
  {
    id: 'something-else',
    room: 'body',
    name: 'Or Is It Something Else?',
    band: 'B',
    move: 'practice',
    trains: 'Telling a feeling from just being hungry',
    opener: 'Careful with this one. Bodies are bad at labels.',
    close: 'A racing heart doesn’t say why it’s racing. Worth checking before you name it.',
    engine: 'sort',
    bins: ['Probably a feeling', 'Probably the body', 'Could be either'],
    binHints: ['something happened', 'food, sleep, running', 'genuinely unclear'],
    rounds: [
      {
        prompt: 'Heart going fast. What’s the most likely cause?',
        cards: [
          { text: 'You just ran up the stairs', bin: 1 },
          { text: 'You’re about to read out loud', bin: 0 },
          { text: 'You haven’t eaten since breakfast', bin: 1 },
          { text: 'You’re watching a scary bit', bin: 0 },
          { text: 'You woke up like this', bin: -1, note: 'Nobody knows this one. Not even doctors, sometimes.' },
        ],
      },
      {
        prompt: 'A heavy, flat, can’t-be-bothered feeling.',
        cards: [
          { text: 'You slept four hours', bin: 1 },
          { text: 'Your friend didn’t message back', bin: 0 },
          { text: 'You’re coming down with something', bin: 1 },
          { text: 'It’s February and it’s dark at four', bin: -1, note: 'Both. Weather does get into people.' },
        ],
      },
    ],
  },
  {
    id: 'secret-feet',
    room: 'body',
    name: 'Secret Feet',
    band: 'A',
    move: 'experiment',
    trains: 'A thread of attention, all day',
    opener: 'This one’s a secret. Nobody can see you playing it.',
    close: 'Your head can be miles away. Your feet are always right here.',
    offScreen: true,
    engine: 'timed',
    beats: [
      { kind: 'say', text: 'Here’s a game nobody can see you playing.' },
      { kind: 'say', text: 'Can you feel your feet? Inside your shoes. Right now.' },
      { kind: 'hold', seconds: 8 },
      { kind: 'ask', prompt: 'Could you feel them?', options: ['Yes', 'Sort of', 'Not really'] },
      { kind: 'reveal', text: 'You can wiggle your toes and nobody will know. That’s it. That’s the whole game.' },
      { kind: 'mission', text: 'Next time you’re waiting — in a queue, in the car, in assembly — find your feet. Nobody will ever know you did it.' },
    ],
  },

  /* ══ Thought Room · 11 ══════════════════════════════════════════════ */
  {
    id: 'quiet-inside',
    room: 'thought',
    name: 'Quiet Inside',
    band: 'A',
    move: 'trapdoor',
    flagship: true,
    trains: 'Meeting the voice in your head',
    opener: 'Easy one to start. Just go quiet in there.',
    close: 'It’s talking right now. About this.',
    engine: 'timed',
    beats: [
      { kind: 'say', text: 'Go quiet inside your head. Completely quiet. No thoughts at all.' },
      { kind: 'say', text: 'Ten seconds. Starting… now.' },
      { kind: 'hold', seconds: 10 },
      { kind: 'ask', prompt: 'So. Did it stay quiet?', options: ['No', 'Not even a bit', 'Nearly', 'Yes'] },
      { kind: 'reveal', text: 'Something started talking, didn’t it. Probably about how this was a weird thing to ask you to do.' },
      { kind: 'say', text: 'That’s the thing we’re looking for. It never stops.', who: 'chirpy' },
    ],
  },
  {
    id: 'camera-or-brain',
    room: 'thought',
    name: 'Camera or Brain?',
    band: 'A',
    move: 'experiment',
    flagship: true,
    trains: 'What happened, and what your mind added',
    opener: 'Pretend you’ve got a camera. Point it at what happened.',
    close: 'Both bits are allowed. They’re just different kinds of bits.',
    engine: 'sort',
    bins: ['The camera saw it', 'Only your brain knows it'],
    binHints: ['out there, in the room', 'in here, where only you are'],
    rounds: [
      {
        prompt: 'Sam took the red car. Sort what’s in the story.',
        cards: [
          { text: 'Sam picked up the red car', bin: 0 },
          { text: 'Sam doesn’t like me any more', bin: 1, note: 'Point the camera at that one. …You can’t, can you.' },
          { text: 'Sam walked to the other table', bin: 0 },
          { text: 'Sam did it on purpose to annoy me', bin: 1 },
          { text: 'I said “hey”', bin: 0 },
        ],
      },
      {
        prompt: 'Nobody sat next to me at lunch.',
        cards: [
          { text: 'The seat next to me was empty', bin: 0 },
          { text: 'Everyone’s decided about me', bin: 1 },
          { text: 'Two people sat at the far end', bin: 0 },
          { text: 'It’s going to be like this all year', bin: 1, note: 'A camera can’t film next Tuesday either.' },
        ],
      },
      {
        prompt: 'I got told off in front of everyone.',
        cards: [
          { text: 'Mr Blake said my name', bin: 0 },
          { text: 'The whole class was staring', bin: -1, note: 'Tricky one. Some of them were. All of them? That bit’s the brain.' },
          { text: 'Everyone thinks I’m the bad one now', bin: 1 },
          { text: 'I sat back down', bin: 0 },
        ],
      },
    ],
  },
  {
    id: 'thought-parade',
    room: 'thought',
    name: 'Thought Parade',
    band: 'A',
    move: 'experiment',
    trains: 'Letting a thought go past',
    opener: 'They’re going to walk past. Don’t catch any.',
    close: 'You let them go past. You didn’t have to do anything about a single one.',
    engine: 'timed',
    beats: [
      { kind: 'say', text: 'Thoughts are about to march past. Your job is to do nothing.' },
      { kind: 'say', text: 'Don’t catch them. Don’t argue with them. Just watch them go.' },
      { kind: 'parade', thoughts: [
        'I’m hungry',
        'This is a weird game',
        'What’s for tea',
        'I should have said something back',
        'Am I doing this right',
        'That song again',
        'I don’t like Tuesdays',
        'Is it nearly over',
      ] },
      { kind: 'ask', prompt: 'Did one of them get you?', options: ['One of them did', 'A few', 'None — I watched them all go', 'I stopped watching'] },
      { kind: 'reveal', text: 'They went past anyway. Every one of them. Whether you joined in or not.' },
    ],
  },
  {
    id: 'purple-elephant',
    room: 'thought',
    name: 'The Purple Elephant',
    band: 'B',
    move: 'trapdoor',
    trains: 'Why pushing a thought away doesn’t work',
    opener: 'Simple instruction. Should be easy.',
    close: 'Telling yourself not to think about something is a really good way to think about it.',
    engine: 'timed',
    beats: [
      { kind: 'say', text: 'For the next ten seconds, do not think about a purple elephant.' },
      { kind: 'say', text: 'Whatever you do. No purple elephant.' },
      { kind: 'hold', seconds: 10 },
      { kind: 'ask', prompt: 'How did that go?', options: ['Elephant', 'Immediate elephant', 'I nearly managed it', 'Loads of elephants'] },
      { kind: 'reveal', text: 'Yeah. Telling yourself not to think about something is a really good way to think about it.' },
    ],
  },
  {
    id: 'are-you-hopping',
    room: 'thought',
    name: 'Are You Hopping?',
    band: 'A',
    move: 'trapdoor',
    trains: 'A thought is not an instruction',
    opener: 'Do exactly what I say. Nothing tricky.',
    close: 'Your brain can say anything it likes. Your legs are yours.',
    engine: 'timed',
    beats: [
      { kind: 'say', text: 'Right now, think about hopping.' },
      { kind: 'say', text: 'Really picture it. Hopping on one leg.' },
      { kind: 'hold', seconds: 5 },
      { kind: 'ask', prompt: '…Are you hopping?', options: ['No', 'No — obviously not', 'I am now', 'I was already'] },
      { kind: 'reveal', text: 'No. Thinking and doing are two different machines.' },
      { kind: 'say', text: 'Which means every thought you’ve ever had that worried you — you didn’t do it. You thought it.', who: 'chirpy' },
    ],
  },
  {
    id: 'say-it-twice',
    room: 'thought',
    name: 'Say It Twice',
    band: 'A',
    move: 'experiment',
    trains: 'You are the one noticing',
    opener: 'Out loud, this one. Properly out loud.',
    close: 'In the second one there are two of you. The cross one — and the one who noticed.',
    engine: 'timed',
    beats: [
      { kind: 'say', text: 'Say this out loud: “I am cross.”' },
      { kind: 'hold', seconds: 4 },
      { kind: 'say', text: 'Now say this: “I notice I am cross.”' },
      { kind: 'hold', seconds: 4 },
      { kind: 'say', text: 'Say them again. Both of them.' },
      { kind: 'hold', seconds: 6 },
      { kind: 'ask', prompt: 'Felt any different?', options: ['Yes', 'A bit', 'Not really', 'The second one felt further away'] },
      { kind: 'reveal', text: 'In the second one there are two of you. The cross one — and the one who noticed.' },
    ],
  },
  {
    id: 'loud-quiet',
    room: 'thought',
    name: 'Loud Thought, Quiet Thought',
    band: 'B',
    move: 'image',
    trains: 'Loud and right are different things',
    opener: 'In a shop, the loudest person is not usually the one who knows the most.',
    close: 'Loud and right are different things.',
    engine: 'dial',
    rounds: [
      { prompt: '“Everyone saw. Everyone.” How loud is that one?', steps: ['a whisper', 'talking', 'raised', 'shouting', 'hammering'], affirm: 'Loud. Now — how much does it actually know?' },
      { prompt: '“Maybe two people noticed and forgot.” How loud is that one?', steps: ['a whisper', 'talking', 'raised', 'shouting', 'hammering'], affirm: 'Quiet. And more likely to be right.' },
      { prompt: '“I’m going to be rubbish at this.” How loud?', steps: ['a whisper', 'talking', 'raised', 'shouting', 'hammering'] },
      { prompt: '“I’ve done harder things than this.” How loud?', steps: ['a whisper', 'talking', 'raised', 'shouting', 'hammering'], affirm: 'The one that keeps hammering isn’t the reliable one. It’s just the loudest one.' },
    ],
  },
  {
    id: 'know-or-guess',
    room: 'thought',
    name: 'Know or Guess?',
    band: 'B',
    move: 'practice',
    trains: 'Telling knowing from guessing',
    opener: 'Neither of these is wrong. They’re just different.',
    close: 'Guessing isn’t bad. Guessing that you know is the tricky bit.',
    engine: 'sort',
    bins: ['I know this', 'My mind guessed this'],
    binHints: ['I could show someone', 'nobody could check it'],
    rounds: [
      {
        prompt: 'She walked past without saying hello.',
        cards: [
          { text: 'She walked past', bin: 0 },
          { text: 'She’s annoyed with me', bin: 1 },
          { text: 'She was looking at her phone', bin: 0 },
          { text: 'She’s been off with me all week', bin: -1, note: 'Half and half. Some of that you saw. Some you joined up.' },
        ],
      },
      {
        prompt: 'I didn’t get picked for the team.',
        cards: [
          { text: 'My name wasn’t read out', bin: 0 },
          { text: 'They think I’m no good', bin: 1 },
          { text: 'Eleven other people were picked', bin: 0 },
          { text: 'I’ll never get picked', bin: 1, note: 'Nobody knows next time. Not even the coach.' },
        ],
      },
    ],
  },
  {
    id: 'sticky-or-floaty',
    room: 'thought',
    name: 'Sticky or Floaty?',
    band: 'A',
    move: 'image',
    trains: 'Some thoughts stick, some drift',
    opener: 'You know when you’ve got a wobbly tooth?',
    close: 'Some thoughts are wobbly teeth. Your tongue keeps going back to them.',
    engine: 'sort',
    bins: ['Floaty — it drifts off', 'Sticky — I keep going back'],
    binHints: ['gone in a second', 'poke, poke, poke'],
    rounds: [
      {
        prompt: 'Sort today’s thoughts.',
        cards: [
          { text: 'What’s for tea', bin: 0 },
          { text: 'That thing I said in front of everyone', bin: 1 },
          { text: 'I need the loo', bin: 0 },
          { text: 'Whether they meant it like that', bin: 1 },
          { text: 'There’s a bird outside', bin: 0 },
          { text: 'What if I get it wrong tomorrow', bin: 1 },
        ],
      },
      {
        prompt: 'And these ones?',
        cards: [
          { text: 'That song', bin: -1, note: 'Songs are the stickiest thing there is and nobody knows why.' },
          { text: 'My sock feels weird', bin: 0 },
          { text: 'Whether they like me', bin: 1 },
        ],
      },
    ],
  },
  {
    id: 'guard-dog',
    room: 'thought',
    name: 'The Guard Dog',
    band: 'A',
    move: 'image',
    trains: 'The worried voice is trying to help',
    opener: 'Your brain has a guard dog.',
    close: 'You wouldn’t get rid of the dog. It’s trying to look after you. You just learn to check.',
    engine: 'choose',
    rounds: [
      { scene: 'Your brain has a guard dog. Its whole job is to bark if something’s coming.', prompt: 'It’s barking. What is it, usually?', options: ['Something actually coming', 'The postman', 'A leaf', 'Next door’s cat'], affirm: 'Sometimes it’s right. Mostly it’s the postman.' },
      { scene: '“Everyone’s going to laugh at you.”', prompt: 'Postman, or actually something?', options: ['Postman', 'Actually something', 'Can’t tell yet'] },
      { scene: '“That car is going too fast — get back.”', prompt: 'Postman, or actually something?', options: ['Postman', 'Actually something', 'Can’t tell yet'], affirm: 'That one’s the dog doing its actual job. You’d want it barking there.' },
      { scene: '“They didn’t reply. They’ve gone off you.”', prompt: 'Postman, or actually something?', options: ['Postman', 'Actually something', 'Can’t tell yet'] },
    ],
  },
  {
    id: 'predictions',
    room: 'thought',
    name: 'Predictions',
    band: 'B',
    move: 'experiment',
    trains: 'Checking what your mind was sure about',
    opener: 'Write down what it’s certain about. I’ll ask you later.',
    close: 'It isn’t you being checked. It’s the prediction being checked. Those are different.',
    engine: 'story',
    panels: [
      { kind: 'line', text: 'Your mind is certain about something that hasn’t happened yet.' },
      { kind: 'line', text: 'Let’s write it down. Then we’ll come back and see.' },
      { kind: 'write', prompt: 'What is your mind sure is going to happen?', placeholder: 'Nobody will talk to me at the party…' },
      { kind: 'choice', prompt: 'How sure is it?', options: ['Completely certain', 'Pretty sure', 'It keeps changing its mind'] },
      { kind: 'line', text: 'Kept. On this device only — nobody else can see it, not even a grown-up, unless you show them.' },
      { kind: 'line', text: 'Come back after it’s happened. I’ll have the question ready.', who: 'chirpy' },
    ],
  },
];
