/**
 * Catalog 3 of 3 — the rooms about other people, big feelings, and looking
 * back. 19 games.
 *
 *   Friendship Room  · 3 · saying the hard thing kindly
 *   Kindness Room    · 3 · kindness, including towards yourself
 *   Big Feelings     · 6 · jealousy, sadness, embarrassment, frustration, disappointment
 *   Reflection Room  · 4 · trains step 8, noticing what you noticed
 *   Together Games   · 3 · played with a grown-up
 *
 * The Friendship and Kindness games are the only ones in the library without
 * a script in MIND_GYM_TEACHING_MOVES.md — those two rooms exist on the live
 * page but not in the master plan's game tables. They are written to the same
 * rules (§"Writing rules for anyone adding to this"): the child supplies the
 * answer, nothing is ever wrong, and the moral is left off the end.
 */

import type { Game } from '../types';

export const CARE_GAMES: Game[] = [
  /* ══ Friendship Room · 3 ════════════════════════════════════════════ */
  {
    id: 'repair-kit',
    room: 'friendship',
    name: 'The Repair Kit',
    band: 'A',
    move: 'practice',
    flagship: true,
    trains: 'Mending it after it breaks',
    opener: 'Something’s broken. Nobody’s in trouble. What have you got?',
    close: 'Every one of those is a real repair. You didn’t need the perfect one.',
    engine: 'choose',
    rounds: [
      { scene: 'You said something in a rush and their face changed.', prompt: 'What could you try?', options: ['Say sorry, and mean it', 'Say what you actually meant', 'Ask if they’re alright', 'Give it a bit, then go back', 'Ask a grown-up to help'], multi: true },
      { scene: 'They won’t let you join in. Again.', prompt: 'What could you try?', options: ['Ask once more, later', 'Say “I’d like a turn”', 'Find someone else today', 'Ask why', 'Tell someone how it’s going'], multi: true },
      { scene: 'They said sorry. You’re still cross.', prompt: 'What’s allowed?', options: ['Say “I’m still a bit cross”', 'Say okay and mean it later', 'Need until tomorrow', 'All of those'], affirm: 'All of those. A sorry doesn’t have to work straight away.' },
    ],
  },
  {
    id: 'join-in',
    room: 'friendship',
    name: 'Asking to Join In',
    band: 'S',
    move: 'experiment',
    trains: 'The hardest six seconds in the playground',
    opener: 'This is the hard bit. The bit before you say anything.',
    close: 'The waiting bit was the hard bit. It’s about six seconds long, and it never gets much longer than that.',
    engine: 'story',
    panels: [
      { kind: 'line', text: 'There’s a game going. You want to be in it.' },
      { kind: 'line', text: 'You’re standing about four steps away.' },
      { kind: 'line', text: 'Your mind says: they’ll say no. They’ll all look. Don’t.' },
      { kind: 'choice', prompt: 'What do you do?', options: ['“Can I play?”', 'Stand nearer and wait', 'Join in and see', 'Ask one person, not all of them', 'Go and do something else today'] },
      { kind: 'replay', text: 'So you {choice}. And then there’s a bit where nothing happens and it’s horrible.' },
      { kind: 'line', text: 'And then it’s over, one way or the other.' },
      { kind: 'choice', prompt: 'They said no.', options: ['That’s rubbish', 'I’ll ask again tomorrow', 'It’s probably not about me', 'I’ll find someone else'] },
      { kind: 'line', text: 'Both endings happen to everyone. The asking was the same either way.', who: 'chirpy' },
    ],
  },
  {
    id: 'sorry-that-lands',
    room: 'friendship',
    name: 'The Sorry That Lands',
    band: 'B',
    move: 'practice',
    trains: 'Why some sorries don’t work',
    opener: 'Some of these are sorries. Some are arguments in a coat.',
    close: 'The ones that land don’t have a “but” in them. That’s nearly the whole difference.',
    engine: 'sort',
    bins: ['This one lands', 'This one doesn’t'],
    binHints: ['they’d feel better', 'they’d feel worse'],
    rounds: [
      {
        prompt: 'Sort the sorries.',
        cards: [
          { text: '“I’m sorry. That was mean.”', bin: 0 },
          { text: '“Sorry, but you started it.”', bin: 1 },
          { text: '“Sorry you got upset.”', bin: 1, note: 'That one’s about them being upset, not about what you did. Slippery.' },
          { text: '“I shouldn’t have said that. Are you okay?”', bin: 0 },
          { text: '“Alright, SORRY.”', bin: 1 },
          { text: '“I didn’t mean it like that, and I’m still sorry it landed like that.”', bin: 0 },
          { text: '“Sorry. What can I do?”', bin: 0 },
        ],
      },
    ],
  },

  /* ══ Kindness Room · 3 ══════════════════════════════════════════════ */
  {
    id: 'warm-light',
    room: 'kindness',
    name: 'Warm Light',
    band: 'A',
    move: 'image',
    flagship: true,
    trains: 'Being somewhere warm for a minute',
    opener: 'Nothing to work out in this one. Just sit in it.',
    close: 'That’s all it is. You can go back there any time — it doesn’t need the app.',
    engine: 'timed',
    beats: [
      { kind: 'say', text: 'Somewhere behind your eyes, there’s a warm light. Like a lamp in a window.' },
      { kind: 'say', text: 'Nothing magic. Just warm.' },
      { kind: 'breath', rounds: 3, shape: 'balloon' },
      { kind: 'say', text: 'Let it be somewhere in your chest. Or your tummy. Wherever it wants to be.' },
      { kind: 'hold', seconds: 12 },
      { kind: 'reveal', text: 'Still there. It was there before we started, honestly.' },
    ],
  },
  {
    id: 'kindness-seeds',
    room: 'kindness',
    name: 'Seeds',
    band: 'S',
    move: 'practice',
    trains: 'Kindness you actually do',
    opener: 'Pick one. Small ones count. Small ones mostly count more.',
    close: 'Now go and do it. That’s the only bit of this game that’s outside.',
    offScreen: true,
    engine: 'choose',
    rounds: [
      { prompt: 'Who’s your kindness for today?', options: ['Someone at home', 'Someone at school', 'Someone having a rotten day', 'Someone I don’t know well', 'Me'] },
      { prompt: 'What will you do?', options: ['Say something nice out loud', 'Help without being asked', 'Include someone', 'Share something', 'Say thank you properly', 'Just sit with them'] },
      { prompt: 'When?', options: ['Today', 'Tomorrow', 'Next time I see them'], affirm: 'Right. That’s a real one. Nobody has to know it came from a game.' },
    ],
  },
  {
    id: 'the-kind-thing-nobody-saw',
    room: 'kindness',
    name: 'The Kind Thing Nobody Saw',
    band: 'A',
    move: 'experiment',
    trains: 'Kindness that got no credit',
    opener: 'There’s one you did that nobody clocked. I want that one.',
    close: 'Nobody said anything about it. It counted anyway.',
    engine: 'story',
    panels: [
      { kind: 'line', text: 'Somewhere in the last week, you did something kind.' },
      { kind: 'line', text: 'And nobody noticed. Nobody said thanks. It just went past.' },
      { kind: 'write', prompt: 'What was it?', placeholder: 'I moved up so someone could sit down…' },
      { kind: 'line', text: 'That happened. It went into the world and stayed there.' },
      { kind: 'choice', prompt: 'Does it count less because nobody saw?', options: ['No', 'A bit', 'It counts more, actually'] },
      { kind: 'line', text: 'Now the harder one.', who: 'chirpy' },
      { kind: 'choice', prompt: 'Would you say that thing you just did was kind — if someone else had done it?', options: ['Yes, obviously', 'Yes — and I wouldn’t say it about me', 'I’d probably make more of it'] },
      { kind: 'line', text: 'Mm. People are like that about their own.' },
    ],
  },

  /* ══ Big Feelings Room · 6 ══════════════════════════════════════════ */
  {
    id: 'jealousy-two-true',
    room: 'bigfeelings',
    name: 'Jealousy: Two True Things',
    band: 'B',
    move: 'image',
    flagship: true,
    trains: 'Happy for them AND jealous',
    opener: 'Both dials. Don’t turn one down to be nice.',
    close: 'Jealous doesn’t cancel pleased. You can be a good friend and still want what they got.',
    engine: 'dial',
    dual: { a: 'Happy for them', b: 'Jealous' },
    rounds: [
      { prompt: 'Your friend got the thing you both wanted.', steps: ['a whisper', 'quite there', 'quite loud', 'all of it'], affirm: 'Both up. That’s allowed, and it’s what most people actually feel.' },
      { prompt: 'They’re brilliant at the thing you’ve been practising for months.', steps: ['a whisper', 'quite there', 'quite loud', 'all of it'] },
      { prompt: 'Someone else got picked to go first.', steps: ['a whisper', 'quite there', 'quite loud', 'all of it'], affirm: 'Jealousy doesn’t make you a bad friend. It makes you someone who wanted something.' },
    ],
  },
  {
    id: 'comparing-machine',
    room: 'bigfeelings',
    name: 'Jealousy: The Comparing Machine',
    band: 'B',
    move: 'experiment',
    trains: 'What the comparison left out',
    opener: 'The machine only shows you one column. Watch.',
    close: 'It showed you a sliver and called it the whole person.',
    engine: 'story',
    panels: [
      { kind: 'line', text: 'Feed someone into the machine. It compares them to you.' },
      { kind: 'cards', prompt: 'Here’s what it prints.', cards: [
        'They’re better at football',
        'They’ve got more friends',
        'They find the work easy',
        'Everyone likes them',
      ], land: 'That’s the machine’s whole answer. Four lines.' },
      { kind: 'line', text: 'Now let’s look at what it didn’t print.' },
      { kind: 'cards', prompt: 'Tap what the machine left out.', cards: [
        'What their week has actually been like',
        'What they’re worried about',
        'What they’re not good at',
        'What they’d swap with you if they could',
        'The bits of them nobody sees',
      ], land: 'It left all of that out. It always does. It only measures one column at a time.' },
      { kind: 'line', text: 'Not because it’s lying. Because that’s all it can see.', who: 'chirpy' },
    ],
  },
  {
    id: 'heavy-things',
    room: 'bigfeelings',
    name: 'Sadness: Heavy Things',
    band: 'A',
    move: 'image',
    trains: 'Sadness isn’t for fixing',
    opener: 'We’re not making this lighter. We’re seeing what helps you carry it.',
    close: 'None of those made it go. They made it carryable. That’s a different job, and it’s the real one.',
    engine: 'dial',
    rounds: [
      { prompt: 'How heavy is it today?', steps: ['light', 'noticeable', 'heavy', 'very heavy', 'can’t put it down'], affirm: 'Okay. That’s where it is. I’m not going to try and talk you out of it.' },
      { prompt: 'Now — being with someone who knows. How much does that help?', steps: ['not at all', 'a bit', 'quite a lot', 'a lot'] },
      { prompt: 'Saying it out loud to one person?', steps: ['not at all', 'a bit', 'quite a lot', 'a lot'] },
      { prompt: 'Time. Just some days going past?', steps: ['not at all', 'a bit', 'quite a lot', 'a lot'], affirm: 'Company and time. That’s mostly the list. It’s a short list and it does work.' },
    ],
  },
  {
    id: 'the-spotlight',
    room: 'bigfeelings',
    name: 'Embarrassment: The Spotlight',
    band: 'B',
    move: 'trapdoor',
    trains: 'Everyone is busy with their own',
    opener: 'Two questions. The second one’s the interesting one.',
    close: 'They’ve forgotten. They were busy cringing about theirs.',
    engine: 'timed',
    beats: [
      { kind: 'say', text: 'Think of something embarrassing you did. Not the worst one. A medium one.' },
      { kind: 'hold', seconds: 7 },
      { kind: 'say', text: 'Got it? Right.' },
      { kind: 'say', text: 'Now — think of something embarrassing that someone else did, in front of you, this year.' },
      { kind: 'hold', seconds: 14 },
      { kind: 'ask', prompt: 'Struggling?', options: ['Yes', 'Can’t think of one', 'Got one, took ages', 'Got one straight away'] },
      { kind: 'reveal', text: 'Everyone is. Everyone remembers their own and almost none of anyone else’s.' },
      { kind: 'say', text: 'Which means the thing you’re still cringing about — they’ve forgotten it.', who: 'chirpy' },
    ],
  },
  {
    id: 'stuck-game',
    room: 'bigfeelings',
    name: 'Frustration: The Stuck Game',
    band: 'A',
    move: 'experiment',
    trains: 'Noticing frustration arrive',
    opener: 'Fair warning: this one is annoying on purpose.',
    close: 'You felt it arrive. That’s worth more than finishing the puzzle would have been.',
    engine: 'timed',
    beats: [
      { kind: 'say', text: 'There’s a shape to get through the gap. The gap is slightly too small.' },
      { kind: 'say', text: 'It is meant to be annoying. There’s no losing and no finishing.' },
      { kind: 'balloon', tries: 4 },
      { kind: 'ask', prompt: 'Where did the fed-up bit turn up first?', options: ['My jaw', 'My hands', 'My chest', 'My whole face', 'I didn’t get fed up'] },
      { kind: 'reveal', text: 'There it is. That’s what frustration feels like arriving, and you caught it live.' },
      { kind: 'say', text: 'It turns up in the same place every time, mostly. Worth knowing where yours is.', who: 'chirpy' },
    ],
  },
  {
    id: 'disappointment-gap',
    room: 'bigfeelings',
    name: 'Disappointment: The Gap',
    band: 'A',
    move: 'practice',
    trains: 'Naming the gap makes it holdable',
    opener: 'There’s the thing you hoped for. And there’s what happened.',
    close: 'You didn’t make the gap smaller. You just looked straight at it, which is most of it.',
    engine: 'choose',
    rounds: [
      { prompt: 'What did you hope for?', options: ['A day that went well', 'Someone to say yes', 'To be picked', 'For it not to change', 'To be good at it'] },
      { prompt: 'And what happened?', options: ['The opposite', 'Nearly, but not quite', 'Nothing at all', 'Something else instead'] },
      { prompt: 'How big is the gap between those two?', options: ['Small', 'Big', 'Enormous', 'Bigger than it should be'], affirm: 'Disappointment is exactly that gap. Nothing else. It’s not you being ungrateful.' },
      { prompt: 'What do you want to do with it?', options: ['Be fed up for a bit', 'Tell someone', 'Try for it again', 'Leave it for today'], affirm: 'All allowed. “Be fed up for a bit” is a proper plan.' },
    ],
  },

  /* ══ Reflection Room · 4 ════════════════════════════════════════════ */
  {
    id: 'discovery-cards',
    room: 'reflection',
    name: 'Discovery Cards',
    band: 'A',
    move: 'practice',
    flagship: true,
    trains: 'Noticing without right answers',
    opener: 'Tap the ones that ring true. Leave the rest.',
    close: 'You worked those out yourself. Nobody told you any of them.',
    engine: 'choose',
    rounds: [
      { prompt: 'What rings true about today?', options: [
        'Feelings come and go',
        'I can pause before I do something',
        'My mind guesses a lot',
        'Two feelings can be true at once',
        'I’m braver than I thought',
        'I’m not sure',
      ], multi: true, affirm: '“I’m not sure” is one of the cards. It’s a real answer, not a gap.' },
      { prompt: 'Anything you’d like to take with you?', options: ['One of those', 'Nothing today', 'All of it', 'Ask me tomorrow'] },
    ],
  },
  {
    id: 'looking-back',
    room: 'reflection',
    name: 'Looking Back',
    band: 'B',
    move: 'experiment',
    trains: 'Proof that feelings change',
    opener: 'Something from a while ago. Let’s see where it is now.',
    close: 'Nobody fixed it. It moved on its own, while you were doing other things.',
    engine: 'story',
    panels: [
      { kind: 'line', text: 'Think of something that was a very big deal a few weeks ago.' },
      { kind: 'write', prompt: 'What was it?', placeholder: 'The thing with…' },
      { kind: 'choice', prompt: 'How big was it then?', options: ['The whole sky', 'Very big', 'Big', 'Quite big'] },
      { kind: 'choice', prompt: 'And how big is it right now, reading it back?', options: ['Still the whole sky', 'Still big', 'Smaller', 'I’d nearly forgotten it'] },
      { kind: 'replay', text: 'From “the whole sky” to “{choice}”. And you didn’t do anything to it.' },
      { kind: 'line', text: 'If it’s still the whole sky, that’s real too, and it’s worth telling a grown-up about.', who: 'chirpy' },
    ],
  },
  {
    id: 'the-sofa',
    room: 'reflection',
    name: 'The Sofa',
    band: 'S',
    move: 'image',
    trains: 'The you that knows where the sofa is',
    opener: 'You know the scary bit in a film?',
    close: 'That second one is always there. Even when a feeling is really big.',
    engine: 'story',
    panels: [
      { kind: 'line', text: 'When you watch a scary bit in a film, you get scared. Properly scared.' },
      { kind: 'choice', prompt: 'And at the same time — do you know you’re on the sofa?', options: ['Yes', 'Sort of', 'Not while it’s happening'] },
      { kind: 'line', text: 'Both at once. The scared you, and the you that knows where the sofa is.' },
      { kind: 'line', text: 'Two of you, in the same room, on the same sofa.' },
      { kind: 'cards', prompt: 'When else does that happen?', cards: [
        'On a rollercoaster',
        'Hiding in hide and seek',
        'Reading something scary in bed',
        'When someone’s pretending to chase me',
        'When I’m properly upset, actually',
      ], land: 'That last one is the one worth knowing about.' },
    ],
  },
  {
    id: 'time-capsule',
    room: 'reflection',
    name: 'Time Capsule',
    band: 'A',
    move: 'practice',
    trains: 'Things shift, and you keep going',
    opener: 'Say something to the you from later.',
    close: 'Kept on this device. Nobody else can read it unless you show them.',
    engine: 'choose',
    rounds: [
      { prompt: 'Who’s it for?', options: ['Me next week', 'Me next month', 'Me when I’m older', 'Me next time this happens'] },
      { prompt: 'What do you want to tell them?', options: [
        'This bit was hard and I did it anyway',
        'Don’t forget it got better last time',
        'I found something out today',
        'Be nice to yourself about this one',
        'I’m alright, actually',
      ] },
      { prompt: 'Anything you want them to remember about right now?', options: ['How it felt', 'What I decided', 'That it passed', 'Nothing — just hello'], affirm: 'Sealed. It’ll be there.' },
    ],
  },

  /* ══ Together Games · 3 ═════════════════════════════════════════════ */
  {
    id: 'feelings-board-game',
    room: 'together',
    name: 'The Feelings Board Game',
    band: 'A',
    move: 'practice',
    flagship: true,
    trains: 'Making it a thing your family says out loud',
    opener: 'Both of you answer. Grown-ups don’t get to skip.',
    close: 'The point wasn’t the answers. It was that you both said some out loud, at the same table.',
    engine: 'story',
    panels: [
      { kind: 'line', text: 'This one needs a grown-up. Go and get one. I’ll wait.', who: 'chirpy' },
      { kind: 'line', text: 'Rule one: whoever lands on a square answers it. Both of you. No skipping.' },
      { kind: 'cards', prompt: 'Roll. Tap a square.', cards: [
        'Name a feeling you had today',
        'Where do you feel worried?',
        'Something that made you laugh this week',
        'A time you got it wrong',
        'What does cross feel like in your body?',
        'Something you were scared of once and aren’t now',
      ], land: 'Now the grown-up answers the same one. Out loud. Properly.' },
      { kind: 'choice', prompt: 'Did they actually answer it?', options: ['Yes', 'They dodged it', 'They said more than I expected'] },
      { kind: 'cards', prompt: 'Another square.', cards: [
        'Something you find hard',
        'A time you said sorry',
        'What helps when you’re sad?',
        'Something you’re looking forward to',
        'A worry you had that turned out to be toast',
      ], land: 'Both of you again. Ten minutes of this is worth more than an hour of anything else in here.' },
    ],
  },
  {
    id: 'guess-my-feeling',
    room: 'together',
    name: 'Guess My Feeling',
    band: 'S',
    move: 'practice',
    trains: 'Reading faces, and making them',
    opener: 'Charades, but feelings. Grown-ups have to do it too.',
    close: 'You can read them, and you can send them. Both directions.',
    engine: 'timed',
    beats: [
      { kind: 'say', text: 'One of you makes the face and the body. The other one guesses.' },
      { kind: 'say', text: 'Then swap. The grown-up has to do it too — that’s the rule.' },
      { kind: 'ask', prompt: 'Who’s going first?', options: ['Me', 'The grown-up'] },
      { kind: 'say', text: 'Right. Here’s your feeling. Don’t show them the screen.' },
      { kind: 'parade', thoughts: ['Furious', 'Shy', 'Delighted', 'Left out', 'Nervous', 'Fed up', 'Proud', 'Confused'] },
      { kind: 'ask', prompt: 'Did they get it?', options: ['Yes', 'No', 'They guessed a different one that also fitted'] },
      { kind: 'reveal', text: 'A different one that also fitted is the most interesting answer there.' },
      { kind: 'mission', text: 'Swap over. Then keep going for as long as it stays funny.' },
    ],
  },
  {
    id: 'story-swap',
    room: 'together',
    name: 'Story Swap',
    band: 'A',
    move: 'experiment',
    trains: 'Two people, one event, two honest stories',
    opener: 'Same moment. You tell it, then they tell it.',
    close: 'Two stories. Neither of you was lying. That’s the whole thing.',
    engine: 'story',
    panels: [
      { kind: 'line', text: 'Pick a moment you were both there for. Ideally one that went a bit wrong.' },
      { kind: 'write', prompt: 'You go first. What happened?', placeholder: 'We were in the kitchen and…' },
      { kind: 'line', text: 'Now hand it over. Grown-up: same moment, your version. Out loud.' },
      { kind: 'choice', prompt: 'How different was theirs?', options: ['Completely different', 'Quite different', 'Nearly the same', 'They remembered a bit I’d forgotten'] },
      { kind: 'line', text: 'Neither of you made anything up. You were both there and you both got a different afternoon.' },
      { kind: 'choice', prompt: 'Was there a bit of theirs you hadn’t thought about?', options: ['Yes', 'No', 'One bit, and it changed it a bit'] },
      { kind: 'line', text: 'That’s the game. Nobody has to agree at the end.', who: 'chirpy' },
    ],
  },
];
