/**
 * Catalog 2 of 3 — the stepping-back rooms. 22 games.
 *
 *   Different Story · 7 · trains steps 5–7, another story that fits
 *   Pause Room      · 7 · trains the gap between what happens and what you do
 *   Anger Room      · 4 · catching anger early, and looking behind it
 *   Worry Room      · 4 · looking at a worry properly
 *
 * The master plan folds anger and worry into one Big Feelings Room. This
 * build keeps them as their own rooms because the live /mindgymforkids page
 * already has an Anger Room and a Worry Room a child may have visited —
 * taking a room away is a worse trade than having eleven of them. The
 * remaining Big Feelings games (jealousy, sadness, embarrassment,
 * frustration, disappointment) are in catalog 3.
 */

import type { Game } from '../types';

export const PERSPECTIVE_GAMES: Game[] = [
  /* ══ Different Story · 7 ════════════════════════════════════════════ */
  {
    id: 'two-endings',
    room: 'story',
    name: 'Two Endings',
    band: 'A',
    move: 'experiment',
    flagship: true,
    trains: 'More than one story fits',
    opener: 'Same beginning. Watch what happens.',
    close: 'Both of them fit what actually happened. That’s the annoying bit, and the good bit.',
    engine: 'choose',
    rounds: [
      { scene: 'You waved at someone across the road. They didn’t wave back.', prompt: 'Story one, or story two?', options: ['They’re ignoring me', 'They didn’t see me'], affirm: 'Both fit. Nothing in what happened tells you which.' },
      { scene: 'Your message has been read. No reply, all evening.', prompt: 'Story one, or story two?', options: ['They don’t want to talk to me', 'They put their phone down and forgot'], affirm: 'Both fit. Still nothing to tell you which.' },
      { scene: 'A grown-up said “we’ll talk about it later” in a flat voice.', prompt: 'Story one, or story two?', options: ['I’m in trouble', 'They’re tired and it’s about something else'] },
      { scene: 'Two people stopped talking when you came in.', prompt: 'Story one, or story two?', options: ['They were talking about me', 'They finished what they were saying'], affirm: 'You can’t know from the outside. Which is genuinely uncomfortable, and genuinely true.' },
    ],
  },
  {
    id: 'four-maybes',
    room: 'story',
    name: 'Four Maybes',
    band: 'S',
    move: 'experiment',
    trains: 'Making other stories yourself',
    opener: 'One story’s no good. Let’s get four.',
    close: 'Four stories. Same walking past. We don’t actually know which one — and that’s the interesting bit.',
    engine: 'story',
    panels: [
      { kind: 'line', text: 'Someone walked past you and didn’t say hello.' },
      { kind: 'line', text: 'Story one: they’re cross with you.' },
      { kind: 'line', text: 'Now let’s make three more. Ready? Go.', who: 'chirpy' },
      { kind: 'cards', prompt: 'Tap the ones that could also be true.', cards: [
        'They didn’t see me',
        'They were in a rush',
        'They were sad about something',
        'They were thinking about dinner',
        'They’re shy today',
        'They didn’t have their glasses on',
      ], land: 'Four stories. Same walking past. Which one is true?' },
      { kind: 'line', text: '…We don’t know! That’s the interesting bit. We don’t actually know.' },
    ],
  },
  {
    id: 'fear-love-story',
    room: 'story',
    name: 'Fear Story / Love Story',
    band: 'B',
    move: 'practice',
    trains: 'Which part of you wrote this',
    opener: 'Two writers in there. One of them is very fast.',
    close: 'Fear stories are never a fault. They came from the part of you that’s trying to get there first.',
    engine: 'sort',
    bins: ['Written by the scared part', 'Written by the warm part'],
    binHints: ['gets there first, protects', 'slower, kinder, also true'],
    rounds: [
      {
        prompt: 'You didn’t get invited. Sort what your mind said.',
        cards: [
          { text: 'Nobody actually likes me', bin: 0 },
          { text: 'It was probably a small thing', bin: 1 },
          { text: 'This will happen every time now', bin: 0 },
          { text: 'I’ve got people who do want me around', bin: 1 },
          { text: 'I should stop trying', bin: 0, note: 'That’s the scared part protecting you. It hurts less if you stop trying. It also costs you everything.' },
        ],
      },
      {
        prompt: 'You’ve got to read out loud tomorrow.',
        cards: [
          { text: 'I’ll get every word wrong', bin: 0 },
          { text: 'I’ve read out loud before and survived', bin: 1 },
          { text: 'Everyone will remember it for years', bin: 0 },
          { text: 'It’ll be over in two minutes', bin: 1 },
        ],
      },
    ],
  },
  {
    id: 'whose-story',
    room: 'story',
    name: 'Whose Story?',
    band: 'A',
    move: 'practice',
    trains: 'Other people are inside their own story',
    opener: 'Same afternoon. Two people. Two completely different afternoons.',
    close: 'Everyone’s walking around inside their own story. Including the person who upset you.',
    engine: 'choose',
    rounds: [
      { scene: 'YOUR STORY: Bea grabbed the last good pen without asking.', prompt: 'What does that make Bea?', options: ['Rude', 'Selfish', 'In a rush', 'I don’t know'] },
      { scene: 'BEA’S STORY: Bea has been told off twice today for not being ready. There was one pen left.', prompt: 'Now what does it look like?', options: ['Still rude', 'A bit different', 'Completely different', 'Both at once'], affirm: 'Both can be true. It can still have been annoying.' },
      { scene: 'Neither of them was lying about their afternoon.', prompt: 'How many true stories were there?', options: ['One', 'Two', 'Two, and neither is the whole thing'] },
    ],
  },
  {
    id: 'tell-a-friend',
    room: 'story',
    name: 'What Would You Tell a Friend?',
    band: 'B',
    move: 'trapdoor',
    trains: 'You are kinder to other people',
    opener: 'Your best friend needs you. What do you say?',
    close: 'That was your own voice. Your own words. They fit you too.',
    engine: 'story',
    panels: [
      { kind: 'line', text: 'Your best friend comes to you and says:' },
      { kind: 'line', text: '“I’m so stupid. I ruined everything. Everyone thinks I’m pathetic.”' },
      { kind: 'write', prompt: 'What do you say to them?', placeholder: 'You’re not stupid…' },
      { kind: 'line', text: 'Nice. Really nice, actually.' },
      { kind: 'line', text: 'Now — that thought was yours. From earlier. You said it about yourself an hour ago.' },
      { kind: 'choice', prompt: 'So… why is what you just said good enough for them and not for you?', options: ['No idea', 'It’s different when it’s me', 'It isn’t different, is it', 'I don’t want to answer that'] },
      { kind: 'line', text: 'That’s allowed as an answer. It’s a hard question and nobody’s got a good one.', who: 'chirpy' },
    ],
  },
  {
    id: 'rewrite-ending',
    room: 'story',
    name: 'Rewrite the Ending',
    band: 'A',
    move: 'experiment',
    trains: 'You get a say in the story',
    opener: 'You didn’t choose what happened. You do get a go at the ending.',
    close: 'The event didn’t change. The ending did. That bit was yours.',
    engine: 'story',
    panels: [
      { kind: 'line', text: 'Here’s the story your mind wrote this morning.' },
      { kind: 'line', text: '“I dropped my tray in the hall. Everyone looked. I’m the person who drops things now.”' },
      { kind: 'choice', prompt: 'Which bit did your mind add?', options: ['I dropped my tray', 'Everyone looked', 'I’m the person who drops things now'] },
      { kind: 'line', text: 'Right. That last bit isn’t an event. It’s an ending someone wrote.' },
      { kind: 'choice', prompt: 'Write a different one. Same tray, same hall.', options: [
        'That was loud and then it was over',
        'People drop things. That was my turn.',
        'Two people helped me pick it up',
        'I’ll mind about it less by Friday',
      ] },
      { kind: 'replay', text: '“I dropped my tray in the hall. Everyone looked. {choice}”' },
      { kind: 'line', text: 'Same beginning. You just changed the last line of it.' },
    ],
  },
  {
    id: 'detective-storyteller',
    room: 'story',
    name: 'Detective vs Storyteller',
    band: 'B',
    move: 'practice',
    trains: 'Evidence, and what got added to it',
    opener: 'Two of them work on every story. Only one of them checks anything.',
    close: 'The storyteller isn’t lying. It’s filling gaps, fast, so you’re not caught out. It just doesn’t say which bits it filled.',
    engine: 'sort',
    bins: ['Evidence', 'The storyteller added it'],
    binHints: ['a camera got it', 'joined up afterwards'],
    rounds: [
      {
        prompt: 'The group chat went quiet after I sent that.',
        cards: [
          { text: 'I sent a message at 8:14', bin: 0 },
          { text: 'Nobody sent one after it', bin: 0 },
          { text: 'They’re all talking about me somewhere else', bin: 1 },
          { text: 'I said the wrong thing', bin: 1 },
          { text: 'It was a Tuesday and it was late', bin: 0, note: 'Boring evidence. Boring evidence is usually the good stuff.' },
        ],
      },
      {
        prompt: 'The teacher moved me to a different table.',
        cards: [
          { text: 'I was moved', bin: 0 },
          { text: 'She’s decided I’m trouble', bin: 1 },
          { text: 'Two other people were moved as well', bin: 0 },
          { text: 'This is going to follow me all year', bin: 1 },
        ],
      },
    ],
  },

  /* ══ Pause Room · 7 ═════════════════════════════════════════════════ */
  {
    id: 'freeze-frame',
    room: 'pause',
    name: 'Freeze Frame',
    band: 'A',
    move: 'experiment',
    flagship: true,
    trains: 'The gap between what happens and what you do',
    opener: 'Watch this. I’m going to stop it in a second.',
    close: 'There’s a gap in there. It’s small, but it’s real, and it’s yours.',
    engine: 'story',
    panels: [
      { kind: 'line', text: 'Ro is building. It’s taken all afternoon.' },
      { kind: 'line', text: 'Someone runs past and knocks the whole thing over.' },
      { kind: 'line', text: 'Ro’s face goes hot. Ro’s hands come up.' },
      { kind: 'line', text: 'STOP.' },
      { kind: 'choice', prompt: 'Right here. What could happen next?', options: ['Shout', 'Push them', 'Walk away', 'Say “that was mine”', 'Breathe first, decide after'] },
      { kind: 'replay', text: 'Play it again. Same knock, same hot face — and this time: {choice}.' },
      { kind: 'line', text: 'The knock didn’t change. Everything after it did.' },
      { kind: 'line', text: 'That stop bit? That’s always there. It’s about half a second long.', who: 'chirpy' },
    ],
  },
  {
    id: 'choose-your-move',
    room: 'pause',
    name: 'Choose Your Move',
    band: 'A',
    move: 'practice',
    trains: 'Every move goes somewhere different',
    opener: 'Five moves. None of them is the right one.',
    close: 'None of them was wrong. They just go to different places.',
    engine: 'choose',
    rounds: [
      { scene: 'Someone calls you a name in front of other people.', prompt: 'What’s your move?', options: ['Shout back', 'Walk away', 'Say “don’t”', 'Get a grown-up', 'Breathe, then decide'], affirm: 'Where does that one end up? Have a think about it for a second.' },
      { scene: 'Your brother is in your room, again, going through your stuff.', prompt: 'What’s your move?', options: ['Shout', 'Take it back', 'Tell him properly', 'Get a grown-up', 'Come back later'] },
      { scene: 'You’ve been told no, and it’s not fair, and it really isn’t.', prompt: 'What’s your move?', options: ['Argue', 'Slam something', 'Ask why', 'Say it’s not fair, calmly', 'Go and be cross somewhere else first'], affirm: 'That last one is a proper move. Being cross somewhere else first is allowed.' },
    ],
  },
  {
    id: 'red-light-green-light',
    room: 'pause',
    name: 'Red Light, Green Light',
    band: 'S',
    move: 'practice',
    trains: 'Stopping when you’re already going',
    opener: 'Go on green. Stop on red. It gets faster.',
    close: 'Stopping when you’re already going is one of the hardest things a body does.',
    engine: 'timed',
    beats: [
      { kind: 'say', text: 'Green means tap. Red means don’t.' },
      { kind: 'say', text: 'There’s no losing. It just gets quicker.' },
      { kind: 'lights', rounds: 10 },
      { kind: 'reveal', text: 'The going is easy. It’s the stopping that takes something.' },
    ],
  },
  {
    id: 'the-itch',
    room: 'pause',
    name: 'The Itch',
    band: 'A',
    move: 'experiment',
    trains: 'Urges get huge, then go',
    opener: 'Find an itch. Anywhere. Arm, nose, ankle.',
    close: 'It got worse. Then it got weird. Then it went — without you doing anything.',
    engine: 'timed',
    beats: [
      { kind: 'say', text: 'Find an itch. Anywhere. Your arm, your nose, your ankle.' },
      { kind: 'say', text: 'Got one? Now don’t scratch it.' },
      { kind: 'say', text: 'Just watch it. Don’t fight it, don’t scratch it. Watch what it does.' },
      { kind: 'hold', seconds: 15 },
      { kind: 'ask', prompt: 'What did it do?', options: ['Got worse', 'Got worse, then went', 'Went weird', 'I scratched it', 'Still there'] },
      { kind: 'reveal', text: 'It got huge, and then it went, all by itself, while you stayed there.' },
      { kind: 'say', text: 'Wanting to shout does exactly that. So does wanting to hit something, or say the mean thing.', who: 'chirpy' },
    ],
  },
  {
    id: 'slow-the-pop',
    room: 'pause',
    name: 'Slow the Pop',
    band: 'S',
    move: 'practice',
    trains: 'Noticing the build-up',
    opener: 'Stop it as late as you dare. Popping isn’t losing.',
    close: 'You could feel it getting close, couldn’t you. Feelings do the same build-up.',
    engine: 'timed',
    beats: [
      { kind: 'say', text: 'A balloon is going to fill up. Stop it whenever you like.' },
      { kind: 'say', text: 'As late as you dare. And if it pops — nothing happens. It’s a balloon.' },
      { kind: 'balloon', tries: 3 },
      { kind: 'reveal', text: 'You could feel it getting close. That feeling — that’s the useful bit.' },
    ],
  },
  {
    id: 'balloon-breath',
    room: 'pause',
    name: 'Balloon Breath',
    band: 'A',
    move: 'practice',
    trains: 'Making a pause you can feel',
    opener: 'Follow the shape. Or just watch it. Both are fine.',
    close: 'Nothing happened. That was the point of it.',
    engine: 'timed',
    beats: [
      { kind: 'say', text: 'A shape is going to grow and shrink. Breathe with it if you want.' },
      { kind: 'say', text: 'Or just watch it. Watching counts.' },
      { kind: 'breath', rounds: 4, shape: 'balloon' },
      { kind: 'reveal', text: 'That’s it. That’s the whole thing. It’s always available and it’s free.' },
    ],
  },
  {
    id: 'try-not-to-laugh',
    room: 'pause',
    name: 'Try Not To Laugh',
    band: 'A',
    move: 'trapdoor',
    trains: 'You cannot squash a feeling',
    opener: 'Quick — try not to laugh.',
    close: 'The harder you hold one down, the harder it pushes back up.',
    engine: 'timed',
    beats: [
      { kind: 'say', text: 'Quick — try not to laugh.' },
      { kind: 'say', text: 'Whatever happens. Straight face.' },
      { kind: 'hold', seconds: 9, label: 'a duck, wearing a hat, going down a slide' },
      { kind: 'ask', prompt: 'How did that go?', options: ['Badly', 'I laughed', 'I nearly held it', 'I smiled at least'] },
      { kind: 'reveal', text: 'Funny thing about feelings. The harder you hold one down, the harder it pushes back up.' },
      { kind: 'say', text: 'Same as trying not to laugh in assembly. Same as trying not to cry when someone asks if you’re okay.', who: 'chirpy' },
      { kind: 'mission', text: 'Next time you’re in the bath: hold a ball under the water. See how long you can keep it down — and what it does the second you let go.' },
    ],
  },

  /* ══ Anger Room · 4 ═════════════════════════════════════════════════ */
  {
    id: 'anger-volcano',
    room: 'anger',
    name: 'Anger: The Volcano',
    band: 'A',
    move: 'image',
    flagship: true,
    trains: 'Catching anger on the way up',
    opener: 'It doesn’t go off from nothing. There’s always a rumble.',
    close: 'Anger has a run-up. Catching it early is the whole trick.',
    engine: 'body',
    rounds: [
      { prompt: 'Before you get cross — where does it start? The very first bit.', need: 1, cantTell: 'I’ve never noticed', affirm: 'That’s your first rumble. Most people never find theirs.' },
      { prompt: 'And then where does it go next?', need: 1, cantTell: 'I don’t know yet' },
      { prompt: 'Where is it when it’s all the way up?', need: 2, affirm: 'By the time it’s there, it’s late. The first place is the useful one.' },
    ],
  },
  {
    id: 'anger-underneath',
    room: 'anger',
    name: 'Anger: What’s Underneath?',
    band: 'B',
    move: 'image',
    trains: 'Looking behind the loud one',
    opener: 'When a dog is scared, what does it do?',
    close: 'Anger isn’t lying to you. It’s standing in front of the thing that’s harder to say.',
    engine: 'story',
    panels: [
      { kind: 'line', text: 'When a dog is scared, what does it do?' },
      { kind: 'line', text: 'It barks. Big and loud and fierce. So you think it’s angry.' },
      { kind: 'line', text: 'It’s not angry. It’s scared, standing in front of the scared with something loud.' },
      { kind: 'line', text: 'People do that too.' },
      { kind: 'choice', prompt: 'Think of the last time you were properly cross. Have a look behind it.', options: ['Hurt', 'Embarrassed', 'Scared', 'Left out', 'Tired', 'Nothing — just cross'] },
      { kind: 'replay', text: 'So: cross, standing in front of {choice}.' },
      { kind: 'line', text: '“Nothing — just cross” is a real answer, by the way. Sometimes cross is the whole thing.', who: 'chirpy' },
      { kind: 'line', text: 'Anger’s very good at getting there first. It takes the hit so the quiet one doesn’t have to.' },
    ],
  },
  {
    id: 'fair-and-not-fair',
    room: 'anger',
    name: 'Not Fair, or Not What I Wanted?',
    band: 'B',
    move: 'practice',
    trains: 'Two different kinds of “not fair”',
    opener: 'Both of these feel identical from inside. They aren’t.',
    close: 'Both of them are allowed to be annoying. Only one of them is unfair.',
    engine: 'sort',
    bins: ['Actually unfair', 'Not what I wanted'],
    binHints: ['a rule bent for someone', 'a rule I didn’t like'],
    rounds: [
      {
        prompt: 'Sort these. Take your time — some are horrible.',
        cards: [
          { text: 'Everyone got a go except me', bin: 0 },
          { text: 'I had to stop playing at bedtime', bin: 1 },
          { text: 'I got told off for what someone else did', bin: 0 },
          { text: 'My sister got a bigger slice', bin: -1, note: 'Genuinely arguable. Some days that’s unfair. Some days it’s a slice.' },
          { text: 'We did maths instead of art', bin: 1 },
          { text: 'They changed the rules once I started winning', bin: 0 },
        ],
      },
    ],
  },
  {
    id: 'shout-and-after',
    room: 'anger',
    name: 'The Shout and the After',
    band: 'A',
    move: 'experiment',
    trains: 'What happens ten minutes later',
    opener: 'The shout is the easy bit. Let’s look at the ten-minutes-later bit.',
    close: 'The cross was fine. It was real. It was the ten minutes after that you were choosing.',
    engine: 'story',
    panels: [
      { kind: 'line', text: 'Ilie’s game got switched off mid-way. No warning.' },
      { kind: 'line', text: 'Ilie shouts. Really shouts. It feels brilliant for about four seconds.' },
      { kind: 'line', text: 'Then: the quiet. Then the grown-up’s face. Then the rest of the evening.' },
      { kind: 'choice', prompt: 'Rewind. What else could Ilie do with all that cross?', options: [
        'Say “that’s not fair” in a big voice, no shouting',
        'Stamp off and come back',
        'Squeeze both fists, then let go',
        'Say “I need a minute”',
      ] },
      { kind: 'replay', text: 'Same switch-off. Same amount of cross. This time: {choice}.' },
      { kind: 'line', text: 'The cross didn’t get smaller. It just went somewhere that didn’t cost the whole evening.' },
    ],
  },

  /* ══ Worry Room · 4 ═════════════════════════════════════════════════ */
  {
    id: 'what-if-tree',
    room: 'worry',
    name: 'Worry: The What-If Tree',
    band: 'B',
    move: 'experiment',
    flagship: true,
    trains: 'Finding where the guessing started',
    opener: 'One worry. Watch how many it turns into.',
    close: 'One thing happened. The rest was a tree your mind grew in about four seconds.',
    engine: 'story',
    panels: [
      { kind: 'line', text: 'It starts with one: “I’ve got a test on Friday.”' },
      { kind: 'cards', prompt: 'Then it branches. Tap each one as it grows.', cards: [
        'What if I fail it',
        'What if everyone else finds it easy',
        'What if they move me down',
        'What if I’m in the bottom group all year',
        'What if I’m just not clever',
      ], land: 'Five worries. From one test.' },
      { kind: 'choice', prompt: 'Which one of those has actually happened?', options: ['The test is on Friday', 'The failing one', 'The bottom group one', 'None of them yet'] },
      { kind: 'line', text: 'One of them is a fact. The rest is guessing that got very confident on the way up.' },
      { kind: 'line', text: 'The tree isn’t wrong to grow. It’s just guessing, in a row, at speed.', who: 'chirpy' },
    ],
  },
  {
    id: 'now-or-not-now',
    room: 'worry',
    name: 'Worry: Now or Not Now?',
    band: 'A',
    move: 'practice',
    trains: 'Most worry lives in the future',
    opener: 'Sort them. Now, or not now.',
    close: 'Nearly all of them were “not now”. Worry mostly lives somewhere that hasn’t happened.',
    engine: 'sort',
    bins: ['Happening now', 'Might happen later'],
    binHints: ['it’s here, in this room', 'it’s in a future somewhere'],
    rounds: [
      {
        prompt: 'Where does each one live?',
        cards: [
          { text: 'My tummy hurts', bin: 0 },
          { text: 'What if I’m sick at school tomorrow', bin: 1 },
          { text: 'It’s dark and I’m on my own', bin: 0 },
          { text: 'What if nobody plays with me on Monday', bin: 1 },
          { text: 'What if the dog dies one day', bin: 1, note: 'That one’s real, and it’s not now. Both of those are true.' },
          { text: 'I don’t know where my grown-up is right this second', bin: 0, note: 'Now. And that’s one to go and check, not to sit with.' },
        ],
      },
    ],
  },
  {
    id: 'smoke-alarm',
    room: 'worry',
    name: 'The Smoke Alarm',
    band: 'S',
    move: 'image',
    trains: 'Your mind is loud because it’s keen',
    opener: 'Have you ever burnt toast?',
    close: 'It’s not broken. It’s just very keen.',
    engine: 'story',
    panels: [
      { kind: 'line', text: 'Have you ever burnt toast and set off the smoke alarm?' },
      { kind: 'line', text: 'Screaming. The whole house. For toast.' },
      { kind: 'choice', prompt: 'Was the alarm being naughty?', options: ['Yes', 'No — it was doing its job', 'A bit of both'] },
      { kind: 'line', text: 'It was doing its job. It just can’t tell the difference between toast and a fire.' },
      { kind: 'line', text: 'Your brain’s got one of those.' },
      { kind: 'line', text: 'It goes off loud, about things that turn out to be toast.' },
      { kind: 'cards', prompt: 'What’s been toast lately?', cards: [
        'A test that turned out fine',
        'A message that meant nothing',
        'A noise downstairs',
        'A grown-up’s face I read wrong',
        'A day I was dreading that was okay',
      ], land: 'Toast. All of it, toast. And the alarm still went off like the house was going.' },
    ],
  },
  {
    id: 'worry-size',
    room: 'worry',
    name: 'How Big Is It Now?',
    band: 'A',
    move: 'experiment',
    trains: 'Worries change size',
    opener: 'Set it where it is right now. No cheating it smaller.',
    close: 'Nobody made it smaller. It just got smaller once someone else could see it.',
    engine: 'dial',
    rounds: [
      { prompt: 'Your worry, right now. How big?', steps: ['a speck', 'small', 'quite big', 'big', 'the whole sky'], affirm: 'Right. That’s where it is. Nobody’s arguing with it.' },
      { prompt: 'Now — how big was it when you woke up?', steps: ['a speck', 'small', 'quite big', 'big', 'the whole sky'] },
      { prompt: 'And how big will it be on Saturday, do you reckon?', steps: ['a speck', 'small', 'quite big', 'big', 'the whole sky'], affirm: 'You just moved it three times without anything actually changing.' },
      { prompt: 'Last one. How big is it now, after all that?', steps: ['a speck', 'small', 'quite big', 'big', 'the whole sky'] },
    ],
  },
];
