/*
  A SUGGESTED REWORDING FOR EVERY TEACHING LINE, with the reason for it.

  Written against the line as it is today (`for`): a suggestion stops
  showing once its line changes, since it was about the old words. Lines
  added or changed on the admin page can ask for fresh ideas instead.
*/

export interface WordingIdea { for: string; text: string; why: string }

export const WORDING_IDEAS: Record<string, WordingIdea> = {
  "room:kind:tagline": { for: "Things grow here when you’re kind. Slowly, but they do.", text: "Plant something kind here. It grows slowly, but it grows.", why: "Turns the welcome into a small invitation, in the garden’s own words." },
  "room:kind:prompt": { for: "Did you use kind words or do something thoughtful today?", text: "Did you say or do something kind today?", why: "Shorter, and “thoughtful” is a hard word for younger children." },
  "room:kind:learnTitle": { for: "Kind is a thing you do, not a thing you are", text: "Kind is something you do", why: "A shorter headline; the card itself says the rest." },
  "room:kind:learnBody": { for: "Nobody is kind all the time — not your friends, not grown-ups, not anybody. Kindness is something you do, one go at a time, and every single time counts on its own. Missing one doesn’t undo the rest.", text: "Nobody is kind all the time. Not your friends, not grown-ups, nobody. Kindness is something you do, one go at a time, and every go counts. Missing one doesn’t undo the rest.", why: "Same message in shorter sentences that read aloud more easily." },
  "room:kind:caughtLine": { for: "Warm one, that. They always are.", text: "That one feels warm. Kind ones always do.", why: "Says what “that” is, so younger children can follow." },
  "room:truth:tagline": { for: "Where you find out what really happened.", text: "This is where we find out what really happened.", why: "A full sentence sounds more natural when Chirpy says it aloud." },
  "room:truth:prompt": { for: "Were you honest today, even when it was hard?", text: "Did you tell the truth today, even when it was hard?", why: "“Tell the truth” is the room’s own phrase, and easier than “honest”." },
  "room:truth:learnTitle": { for: "The hardest truths are the small ones", text: "Small truths are the tricky ones", why: "Matches the card, which calls them “the tricky ones”." },
  "room:truth:learnBody": { for: "Big lies are easy to spot. The tricky ones are tiny — “it wasn’t me”, “I already did it”, “I only had one”. Telling a small truth when nobody would ever know is the whole skill. That’s the one worth practising.", text: "Big lies are easy to spot. The tricky ones are tiny: “It wasn’t me.” “I already did it.” “I only had one.” Telling a small truth when nobody would ever know is the whole skill.", why: "Ends on the idea itself; “worth practising” tips it into a lesson." },
  "room:truth:caughtLine": { for: "Ooh, that one’s heavy. The honest ones usually are.", text: "Ooh, that one’s heavy. True ones often are.", why: "“True” is simpler than “honest”, and “often” is gentler than “usually”." },
  "room:choices:tagline": { for: "Brave isn’t not scared. Brave is scared and doing it anyway.", text: "Brave means scared, and doing it anyway.", why: "Same idea without the double negative “isn’t not”, which trips young readers." },
  "room:choices:prompt": { for: "Did you choose something safe and respectful today?", text: "Did you stop and make a good choice today?", why: "“Respectful” is abstract; stopping to choose is something a child remembers doing." },
  "room:choices:learnTitle": { for: "There’s a gap between what happens and what you do", text: "There’s a tiny gap before you choose", why: "A shorter headline that still points at the gap." },
  "room:choices:learnBody": { for: "Something happens. Then you do something. In between there’s a gap — usually about one breath long. The gap is where you get to choose. It’s small, but it’s always there, and it gets bigger with practice.", text: "Something happens. Then you do something. In between there’s a gap, about one breath long. That gap is where you choose. Next time something happens, see if you can find it.", why: "Ends on an experiment the child can try, instead of a promise." },
  "room:choices:caughtLine": { for: "That one took a bit of nerve. I felt it from here.", text: "That took a bit of nerve. I could feel it from here.", why: "A touch smoother when read aloud." },
  "room:include:tagline": { for: "Nobody plays alone here unless they want to.", text: "Nobody has to play alone here. Unless they want to.", why: "“Has to” makes it about choice, which is what the room is about." },
  "room:include:prompt": { for: "Did you help someone feel welcome or make a new friend?", text: "Did you help someone feel welcome today?", why: "A new friend isn’t possible most days; helping someone feel welcome always is." },
  "room:include:weekendPrompt": { for: "Did you make sure nobody got left out today?", text: "Did you let someone join in today?", why: "Something concrete a child can picture doing at home." },
  "room:include:learnTitle": { for: "Being left out hurts in your body", text: "Being left out is a real kind of hurt", why: "Says the surprising part plainly; the card explains why." },
  "room:include:learnBody": { for: "Scientists checked: being left out lights up the same bits of your brain as being hurt. That’s why it feels so bad — it genuinely is a kind of hurt. It’s also why letting someone in matters more than it looks like it does.", text: "Scientists found that being left out lights up the same parts of your brain as getting hurt. That’s why it feels so bad: it really is a kind of hurt. And it’s why letting someone in matters more than it looks.", why: "Simpler words (“found”, “parts”) for younger readers." },
  "room:include:caughtLine": { for: "That light’s for someone else as much as you.", text: "That light is for someone else as much as for you.", why: "Spelling out “light is” helps early readers." },
  "room:body:tagline": { for: "Your body knows things before you do.", text: "Your body often knows how you feel before you do.", why: "Says what the body knows, so the idea lands." },
  "room:body:prompt": { for: "Did you eat well, move, or rest your body today?", text: "Did you look after your body today: food, water, moving or rest?", why: "Adds water, and avoids judging what “eating well” means." },
  "room:body:learnTitle": { for: "Tired and sad feel almost the same", text: "Tired and sad can feel almost the same", why: "“Can” keeps it true; they aren’t always the same." },
  "room:body:learnBody": { for: "A lot of the time when everything seems terrible, you’re actually just tired, or hungry, or you haven’t moved all day. It’s worth checking those first — not because your feelings aren’t real, but because sometimes the fix is a sandwich.", text: "Sometimes when everything feels terrible, you’re actually tired, or hungry, or you haven’t moved all day. Check those first. Your feelings are still real, but sometimes the fix is a sandwich.", why: "Shorter sentences, same joke at the end." },
  "room:body:caughtLine": { for: "Steady little glow. Bodies like being noticed.", text: "A steady little glow. Your body liked that.", why: "Speaks about the child’s own body rather than bodies in general." },
  "room:help:tagline": { for: "Small helps count. Most helps are small.", text: "Small helps count, and most helps are small.", why: "One sentence flows better when Chirpy says it aloud." },
  "room:help:prompt": { for: "Did you help family, a classmate, or a friend today?", text: "Did you help someone today, at home or at school?", why: "Shorter, and nobody is left off the list." },
  "room:help:weekendPrompt": { for: "Did you help out at home, or help a friend?", text: "Did you help someone today?", why: "Short and open: any help counts, wherever it happened." },
  "room:help:learnTitle": { for: "Helping without being asked is a different thing", text: "Helping before anyone asks", why: "A short headline a child can picture." },
  "room:help:learnBody": { for: "Doing what you’re told is fine. Noticing that something needs doing and just doing it is a whole other skill, and it’s much rarer. Grown-ups notice it far more than they let on.", text: "Doing what you’re told is fine. Spotting that something needs doing, and just doing it, is a different skill, and it’s much rarer. Grown-ups notice it more than they say.", why: "Simpler words, same surprise at the end." },
  "room:help:caughtLine": { for: "Nobody asked you to catch that one, did they.", text: "Nobody asked you to catch that one, did they?", why: "A question mark helps Chirpy’s voice rise in the right place." },
  "room:mindheart:tagline": { for: "Where you look back at what you found.", text: "This is where you look back at what you found.", why: "A full sentence sounds more natural read aloud." },
  "room:mindheart:prompt": { for: "Did you take quiet time — gratitude, reflection, learning?", text: "Did you have some quiet time today, to think or to say thank you?", why: "Swaps “gratitude” and “reflection” for words a young child uses." },
  "room:mindheart:learnTitle": { for: "You can watch your own mind working", text: "You can watch yourself think", why: "Shorter, and more surprising." },
  "room:mindheart:learnBody": { for: "Here’s the strange bit: you can notice yourself thinking. The part that notices isn’t the same as the thought. Once you’ve spotted that once, you can’t really un-spot it — and it’s the most useful thing in this whole building.", text: "Here’s the strange bit: you can notice yourself thinking. The part of you that notices isn’t the thought. Try it: think of a cat, then notice that you thought it. That noticing is the most useful thing in this whole building.", why: "Adds a tiny experiment, so the child catches it happening." },
  "room:mindheart:caughtLine": { for: "The quiet ones shine longest. Odd, that.", text: "Quiet ones shine the longest. Funny, that.", why: "“Funny” is the word younger children use for odd." },
  "affirm:brave:0": { for: "I am brave, even when I'm scared.", text: "I can feel scared and still be brave.", why: "Lets both feelings be true at once, which is easier to believe." },
  "affirm:brave:1": { for: "I can do hard things.", text: "I can do hard things, one bit at a time.", why: "Adds a how, so it’s believable on a hard day." },
  "affirm:brave:2": { for: "My courage grows every day.", text: "Every time I try, my brave gets a little bigger.", why: "Ties growing braver to trying, which a child can see happen." },
  "affirm:brave:3": { for: "I am stronger than my fears.", text: "I can be scared and still choose what I do.", why: "Doesn’t ask the child to beat the fear, only to choose." },
  "affirm:brave:4": { for: "I choose to be brave, step by step.", text: "I can take one small brave step.", why: "One step is easier to believe than a promise to be brave." },
  "affirm:brave:5": { for: "Fear doesn't stop me from trying.", text: "I can try even when I feel scared.", why: "Says it the positive way round; easier to say and mean." },
  "affirm:brave:6": { for: "I believe in my own strength.", text: "I’ve done hard things before.", why: "Points at real evidence instead of asking for belief." },
  "affirm:brave:7": { for: "I can face anything with courage.", text: "I can face this, one breath at a time.", why: "“Anything” is a big claim; “this” is about right now." },
  "affirm:brave:8": { for: "My brave heart leads the way.", text: "My brave heart is with me today.", why: "Simpler, and doesn’t promise it will always lead." },
  "affirm:brave:9": { for: "I am brave, and I keep going.", text: "I keep going, even when it’s hard.", why: "Describes something the child can actually do." },
  "affirm:calm:0": { for: "I can find peace inside myself.", text: "I can find a quiet place inside me.", why: "A quiet place is easier to imagine than “peace”." },
  "affirm:calm:1": { for: "My breath brings me calm.", text: "Slow breaths help me feel calm.", why: "Says what to do with the breath." },
  "affirm:calm:2": { for: "I am safe, and I can relax.", text: "I can let my shoulders drop and breathe slowly.", why: "Gives a body cue, and doesn’t promise a safety the app can’t know about." },
  "affirm:calm:3": { for: "Peace lives in me right now.", text: "There’s a calm bit inside me, even now.", why: "Concrete, and believable when things feel busy." },
  "affirm:calm:4": { for: "I choose calm over worry.", text: "I can let my worry sit down for a minute.", why: "Doesn’t ask the child to get rid of worry, only to rest it." },
  "affirm:calm:5": { for: "My mind is clear and peaceful.", text: "My mind can slow down, like a snow globe settling.", why: "A picture a child can see, instead of a claim that may feel untrue." },
  "affirm:calm:6": { for: "I take one slow breath at a time.", text: "One slow breath, then another.", why: "Even simpler, and easy to do while saying it." },
  "affirm:calm:7": { for: "Calm is my natural state.", text: "I can come back to calm, again and again.", why: "Few children feel calm is natural; coming back to it is true." },
  "affirm:calm:8": { for: "I let worries float away gently.", text: "I can let my worries float off like bubbles.", why: "A picture makes letting go easier to imagine." },
  "affirm:calm:9": { for: "Peace is always within reach.", text: "Calm is only a few slow breaths away.", why: "Concrete: says how to reach it." },
  "affirm:kind:0": { for: "Kindness starts with me.", text: "I can start the kindness.", why: "Shorter, and an action rather than a slogan." },
  "affirm:kind:1": { for: "I am kind to others and myself.", text: "I can be kind to others, and to me too.", why: "“Can” keeps it true on a day they weren’t." },
  "affirm:kind:2": { for: "My kindness makes a difference.", text: "One kind thing can change someone’s day.", why: "Concrete and easy to believe." },
  "affirm:kind:3": { for: "I choose love and gentleness today.", text: "Today I can choose gentle hands and gentle words.", why: "Says what gentleness looks like." },
  "affirm:kind:4": { for: "Kindness grows when I share it.", text: "Kindness spreads when I share it.", why: "“Spreads” is easier to picture than “grows”." },
  "affirm:kind:5": { for: "I am kinder every single day.", text: "Every kind thing I do counts.", why: "“Kinder every day” can feel untrue; this always is." },
  "affirm:kind:6": { for: "My words and actions are kind.", text: "I can choose kind words, even when I’m cross.", why: "Admits the hard moment, which makes it believable." },
  "affirm:kind:7": { for: "Kindness is my superpower.", text: "Being kind is a kind of strong.", why: "Keeps the fun without a claim a child might doubt." },
  "affirm:kind:8": { for: "I spread warmth wherever I go.", text: "I can bring a bit of warmth wherever I go.", why: "“A bit” keeps it honest." },
  "affirm:kind:9": { for: "My kind heart changes the world.", text: "My kindness changes my bit of the world.", why: "Shrinks a world-sized claim to one a child can see." },
  "affirm:belonging:0": { for: "I belong right here, right now.", text: "There’s room for me here.", why: "A picture of belonging a child can feel." },
  "affirm:belonging:1": { for: "I am worthy of love and friendship.", text: "I deserve friends who are kind to me.", why: "“Worthy” is an adult word; “deserve” is clearer." },
  "affirm:belonging:2": { for: "I belong, even when I'm different.", text: "Being different doesn’t stop me belonging.", why: "Names the worry first, then answers it." },
  "affirm:belonging:3": { for: "My voice matters in this world.", text: "What I say matters.", why: "Shorter, and closer to home than “this world”." },
  "affirm:belonging:4": { for: "I am exactly where I need to be.", text: "I’m allowed to be here, just as I am.", why: "“Exactly where I need to be” is hard for a child to feel." },
  "affirm:belonging:5": { for: "People care about me, truly.", text: "There are people who care about me.", why: "Easier to believe on a lonely day." },
  "affirm:belonging:6": { for: "I belong to a community that loves me.", text: "I have people who are on my side.", why: "“Community” is an adult word." },
  "affirm:belonging:7": { for: "My place in this world is real.", text: "There’s a place for me.", why: "Simpler and warmer." },
  "affirm:belonging:8": { for: "I am accepted, just as I am.", text: "I’m okay just as I am.", why: "“Accepted” depends on other people; “okay” doesn’t." },
  "affirm:belonging:9": { for: "Belonging is my birthright.", text: "I belong, just because I’m me.", why: "“Birthright” is an adult word; this says the same thing." },
  "affirm:try_again:0": { for: "I can try again and do better.", text: "I can try again.", why: "“Do better” adds pressure; trying again is enough." },
  "affirm:try_again:1": { for: "Mistakes help me learn and grow.", text: "Mistakes are how I learn.", why: "Shorter and easier to remember." },
  "affirm:try_again:2": { for: "Every new day brings a fresh start.", text: "I can start again whenever I need to.", why: "A fresh start doesn’t have to wait for tomorrow." },
  "affirm:try_again:3": { for: "I am getting better every time.", text: "I’m getting better, a bit at a time.", why: "“Every time” isn’t always true; “a bit at a time” is." },
  "affirm:try_again:4": { for: "I choose to try once more.", text: "I can have one more go.", why: "Everyday words a child would use." },
  "affirm:try_again:5": { for: "My effort matters, even when I stumble.", text: "Trying counts, even when it goes wrong.", why: "Simpler than “effort” and “stumble”." },
  "affirm:try_again:6": { for: "I learn something new each time I try.", text: "Each time I try, I find out something new.", why: "“Find out” is how children talk about learning." },
  "affirm:try_again:7": { for: "I am resilient and I bounce back.", text: "I can bounce back, like a ball.", why: "“Resilient” is an adult word; the ball is a picture." },
  "affirm:try_again:8": { for: "Tomorrow is a new chance for me.", text: "Tomorrow, I get another go.", why: "Everyday words." },
  "affirm:try_again:9": { for: "I grow stronger with every try.", text: "Each try makes me a little stronger.", why: "“A little” keeps it believable." },
  "affirm:other:0": { for: "I am enough, just as I am.", text: "I don’t have to be perfect to be loved.", why: "Says what “enough” means for a child." },
  "affirm:other:1": { for: "Good things are coming my way.", text: "Good things can still happen today.", why: "A promise about the future can’t be kept; “can” stays true." },
  "affirm:other:2": { for: "I am grateful for this moment.", text: "I can find one good thing about right now.", why: "Gives the child something to do, not a feeling to have." },
  "affirm:other:3": { for: "My future is bright and full.", text: "I wonder what I’ll do next.", why: "Swaps a big promise for curiosity a child can feel." },
  "affirm:other:4": { for: "I choose happiness today.", text: "I can notice the happy bits of today.", why: "Happiness can’t always be chosen; noticing it can." },
  "affirm:other:5": { for: "I am learning and growing.", text: "I’m learning new things all the time.", why: "Concrete, and “growing” can be confused with getting taller." },
  "affirm:other:6": { for: "My feelings matter and are valid.", text: "All my feelings are allowed.", why: "“Valid” is an adult word; “allowed” is how children say it." },
  "affirm:other:7": { for: "I can create the life I want.", text: "I can make good things happen, one small step at a time.", why: "A child-sized version of a grown-up idea." },
  "affirm:other:8": { for: "Every moment is a new beginning.", text: "I can start again, right now.", why: "Concrete, and easy to say in the moment." },
  "affirm:other:9": { for: "I am becoming who I want to be.", text: "Every day I get to choose how I want to be.", why: "Today-sized, and in the child’s hands." },
  "another:rejection:0": { for: "Maybe they were busy and it had nothing to do with me.", text: "Maybe they were busy. It might not be about me at all.", why: "Two short sentences, and “might” keeps it a possibility." },
  "another:rejection:1": { for: "Maybe they didn't notice me, not that they don't like me.", text: "Maybe they just didn’t notice me. That’s not the same as not liking me.", why: "Clearer; the original is hard to follow read aloud." },
  "another:rejection:2": { for: "One person saying no doesn't mean everyone would.", text: "One no doesn’t mean everyone would say no.", why: "Shorter and easier to say." },
  "another:rejection:3": { for: "I can ask again another day.", text: "I could ask again another day.", why: "“Could” feels like an option, not an instruction." },
  "another:rejection:4": { for: "There are other people who do want me around.", text: "Someone else might love to play with me.", why: "A possibility is easier to believe right after a no." },
  "another:rejection:5": { for: "This one time doesn't decide what always happens.", text: "One time isn’t every time.", why: "Short enough to remember and say to yourself." },
  "another:rejection:6": { for: "I can find someone else to play or talk with.", text: "I could look for someone else to play with.", why: "“Could” and “look for” make it a small, doable step." },
  "another:rejection:7": { for: "Being left out once still leaves room for next time.", text: "Being left out today doesn’t mean I’ll be left out tomorrow.", why: "Clearer than “leaves room for next time”." },
  "another:failure:0": { for: "A mistake is something I did, not who I am.", text: "I made a mistake. I’m not a mistake.", why: "Shorter, and easy to remember." },
  "another:failure:1": { for: "I can try again and get a little better.", text: "I can have another go and get a bit better.", why: "Everyday words." },
  "another:failure:2": { for: "Everyone gets things wrong while they're still learning.", text: "Everyone gets things wrong when they’re learning. Even grown-ups.", why: "Adding grown-ups makes it feel true." },
  "another:failure:3": { for: "This one try doesn't decide how good I'll get.", text: "One go doesn’t show how good I’ll get.", why: "Shorter and simpler." },
  "another:failure:4": { for: "I can ask for help instead of doing it alone.", text: "I can ask someone to help me.", why: "Simpler, and leaves out the idea of being alone." },
  "another:failure:5": { for: "My best today can still grow tomorrow.", text: "My best can get better tomorrow.", why: "Clearer than a best that “grows”." },
  "another:failure:6": { for: "Getting it wrong is part of how brains learn.", text: "Getting it wrong is how brains learn. Mine too.", why: "Brings it back to the child." },
  "another:failure:7": { for: "I've figured out hard things before.", text: "I’ve worked out hard things before.", why: "“Worked out” is the everyday phrase for younger children." },
  "another:unfairness:0": { for: "Maybe there's a reason I don't know about yet.", text: "Maybe there’s a reason I can’t see yet.", why: "“Can’t see yet” suggests the reason may come clear." },
  "another:unfairness:1": { for: "I can tell someone it felt unfair to me.", text: "I can tell someone, “That felt unfair to me.”", why: "Gives the child the actual words to use." },
  "another:unfairness:2": { for: "Rules aren't always about me — sometimes they're just rules.", text: "Some rules aren’t about me. They’re just rules.", why: "Shorter sentences." },
  "another:unfairness:3": { for: "This one time going wrong is not proof it always will.", text: "It went wrong this time. That doesn’t mean it always will.", why: "“Proof” is a hard word; two short sentences are clearer." },
  "another:unfairness:4": { for: "I can ask why, instead of guessing the worst reason.", text: "I can ask why, instead of guessing the worst.", why: "A little shorter, same idea." },
  "another:unfairness:5": { for: "It's okay to feel upset and still be safe.", text: "I can feel really cross and still keep everyone safe.", why: "Says what being safe means when you’re cross." },
  "another:unfairness:6": { for: "Next time might go differently.", text: "Next time might be fairer.", why: "Names the thing the child is hoping for." },
  "another:unfairness:7": { for: "I can say what I need without it becoming a fight.", text: "I can say what I need in a calm voice.", why: "Tells the child how, instead of what to avoid." },
  "another:uncertainty:0": { for: "Not knowing yet doesn't mean something bad is coming.", text: "Not knowing yet doesn’t mean it will be bad.", why: "A simpler ending, same idea." },
  "another:uncertainty:1": { for: "I can wait and see what actually happens.", text: "I can wait and see what really happens.", why: "“Really” is a younger child’s word." },
  "another:uncertainty:2": { for: "I've gotten through not-knowing before.", text: "I’ve been unsure before, and I was okay.", why: "“Not-knowing” as a noun is hard to follow." },
  "another:uncertainty:3": { for: "Feeling unsure doesn't mean I'm unsafe.", text: "Feeling wobbly inside doesn’t mean something is wrong.", why: "Names the feeling in body words, without promising safety." },
  "another:uncertainty:4": { for: "I can ask a grown-up what to expect.", text: "I can ask a grown-up what’s going to happen.", why: "“What to expect” is an adult phrase." },
  "another:uncertainty:5": { for: "New things feel strange right up until they suddenly don’t.", text: "New things feel strange, until one day they don’t.", why: "Slightly shorter; keeps the nice surprise at the end." },
  "another:uncertainty:6": { for: "My mind is guessing right now — a guess isn't a fact.", text: "My brain is guessing. A guess isn’t the same as knowing.", why: "“Knowing” is easier than “fact” for younger children." },
  "another:uncertainty:7": { for: "I can take one small step and see what happens next.", text: "I can take one small step, then see.", why: "Shorter." },
  "another:loss:0": { for: "It's okay to miss something and still be okay.", text: "I can miss it and still be okay.", why: "Avoids saying “okay” twice." },
  "another:loss:1": { for: "This ending doesn't erase the good parts that happened.", text: "It ended, but the good bits still happened.", why: "“Erase” is abstract; this says it plainly." },
  "another:loss:2": { for: "I can still remember it even though it changed.", text: "Things change, but I can keep remembering.", why: "Smoother when read aloud." },
  "another:loss:3": { for: "Feeling sad about this makes sense — it mattered to me.", text: "I feel sad because it mattered to me. That makes sense.", why: "Puts the reason first, which comforts." },
  "another:loss:4": { for: "New things can still come, even after this.", text: "Good things can still come, even after this.", why: "“Good things” is warmer than “new things”." },
  "another:loss:5": { for: "I don't have to feel better right away.", text: "I don’t have to feel better yet.", why: "“Yet” quietly says it will come." },
  "another:loss:6": { for: "I can talk about it with someone who'll listen.", text: "I can tell someone who will listen.", why: "Shorter." },
  "another:loss:7": { for: "This is hard, and I can get through hard things.", text: "This is hard. I’ve got through hard things before.", why: "Points at the child’s own past, which is easier to believe." },
  "another:conflict:0": { for: "We can both feel upset and still fix it.", text: "We’re both upset, and we can still make up.", why: "“Make up” is how children talk about fixing a friendship." },
  "another:conflict:1": { for: "One argument doesn't undo a whole friendship.", text: "One argument doesn’t end a whole friendship.", why: "“End” is clearer than “undo”." },
  "another:conflict:2": { for: "Maybe they were having a hard moment, not just being mean.", text: "Maybe they were having a bad day, not trying to be mean.", why: "“Bad day” is familiar; “trying” gently questions the motive." },
  "another:conflict:3": { for: "I can take some space and come back to talk later.", text: "I can take a break and talk about it later.", why: "“Take a break” is easier to picture than “take some space”." },
  "another:conflict:4": { for: "Disagreeing doesn't mean the friendship is over.", text: "Friends can disagree and still be friends.", why: "Says it the positive way round." },
  "another:conflict:5": { for: "I can tell a grown-up if I need help sorting it out.", text: "A grown-up can help us sort it out.", why: "Makes asking for help sound normal, not like telling on someone." },
  "another:conflict:6": { for: "We can both be right about how we feel, even if the story differs.", text: "We can both feel how we feel, even if we remember it differently.", why: "“The story differs” is hard to follow." },
  "another:conflict:7": { for: "I can say sorry, or wait for one, without rushing it.", text: "Sorry can wait until we’re both ready.", why: "Shorter, and takes the pressure off both children." },
  "another:pressure:0": { for: "I don't have to be perfect to be doing okay.", text: "I don’t have to be perfect. Okay is good enough.", why: "Two short sentences land better than one long one." },
  "another:pressure:1": { for: "I can do this one step at a time.", text: "One step at a time. Just the next one.", why: "Even smaller: only the next step matters now." },
  "another:pressure:2": { for: "Asking for more time isn't the same as failing.", text: "Asking for more time is allowed.", why: "Positive wording, without the word “failing”." },
  "another:pressure:3": { for: "Other people feel this pressure too, not just me.", text: "Lots of people feel this way, not just me.", why: "“This way” is easier than “this pressure”." },
  "another:pressure:4": { for: "I can do my best without doing everything.", text: "My best doesn’t have to be everything.", why: "Shorter." },
  "another:pressure:5": { for: "It's okay to say I need help with this.", text: "I can say, “I need help with this.”", why: "Gives the child the exact words to use." },
  "another:pressure:6": { for: "One deadline doesn't decide how capable I am.", text: "One test doesn’t show everything I can do.", why: "“Deadline” and “capable” are adult words." },
  "another:pressure:7": { for: "I can rest and still get where I’m going.", text: "Resting is part of getting there.", why: "Shorter, and makes rest part of the plan." },
  "another:comparison:0": { for: "Someone else's good day doesn't take away from mine.", text: "Their good day doesn’t make mine smaller.", why: "“Smaller” is easier to picture than “take away from”." },
  "another:comparison:1": { for: "I'm not behind — I'm just on my own timeline.", text: "I’m not behind. I’m going at my own speed.", why: "“Timeline” is an adult word." },
  "another:comparison:2": { for: "I can be happy for them and still like myself.", text: "I can be happy for them and happy with me.", why: "A little rhythm makes it easy to remember." },
  "another:comparison:3": { for: "Different doesn't mean less.", text: "Different isn’t worse. It’s just different.", why: "“Worse” is the word children actually worry about." },
  "another:comparison:4": { for: "I have things that are just mine to be proud of.", text: "There are things I’m proud of that are just mine.", why: "Smoother word order." },
  "another:comparison:5": { for: "Comparing myself to them doesn't tell the whole story.", text: "I only see part of their story.", why: "Simpler, and explains why comparing misleads." },
  "another:comparison:6": { for: "I can notice what I have instead of what I don’t.", text: "I can look at what I’ve got, not what I haven’t.", why: "Everyday words." },
  "another:comparison:7": { for: "Everyone starts somewhere different — that's not a race.", text: "Everyone starts in a different place. It isn’t a race.", why: "Two short sentences, easier read aloud." },
  "another:bright:0": { for: "This good feeling is real, and I can let it stay.", text: "This good feeling is real. I can let it stay a while.", why: "“A while” makes it easier to enjoy without holding on." },
  "another:bright:1": { for: "I get to enjoy this without waiting for something to go wrong.", text: "I can just enjoy this.", why: "Shorter, and doesn’t plant the idea that something will go wrong." },
  "another:bright:2": { for: "I made this happen — I can be proud of that.", text: "I helped make this happen. I can feel proud.", why: "“Helped” fits most good moments, which are shared." },
  "another:bright:3": { for: "Good moments count too, not just hard ones.", text: "Good moments count too.", why: "Shorter, and doesn’t bring up hard ones." },
  "another:bright:4": { for: "I can remember this the next time things feel tough.", text: "I can save this feeling for a tough day.", why: "Gives a picture: keeping it for later." },
  "another:bright:5": { for: "This is a sign more good things are possible.", text: "More good things can happen, like this one did.", why: "Points at this moment as the evidence." },
  "another:bright:6": { for: "I did that, and it matters.", text: "I did that. It matters.", why: "Two short beats feel stronger." },
  "another:bright:7": { for: "I can share this good feeling with someone I love.", text: "I can tell someone I love about this.", why: "Says how to share it." },
};
